<?php
declare(strict_types=1);

function tegh_statement_xml_v5990(string $xml): DOMDocument
{
    if(strlen($xml)>48_000_000||preg_match('/<!\s*(?:DOCTYPE|ENTITY)/i',$xml))fail('The workbook contains unsafe XML.',422,'statement_workbook_unsafe');
    $old=libxml_use_internal_errors(true);try{$doc=new DOMDocument();$doc->resolveExternals=false;$doc->substituteEntities=false;if(!$doc->loadXML($xml,LIBXML_NONET|LIBXML_NOBLANKS))fail('The workbook XML is malformed.',422,'statement_workbook_invalid');return $doc;}finally{libxml_clear_errors();libxml_use_internal_errors($old);}
}

function tegh_statement_xlsx_column_v5990(string $letters): int
{
    $index=0;foreach(str_split($letters) as $letter)$index=$index*26+(ord($letter)-64);return $index-1;
}

function tegh_statement_xlsx_date_v5990(string $value,bool $date1904): string
{
    if(preg_match('/^-?\d+(?:\.0+)?$/D',$value)){$serial=(int)$value;$minimum=$date1904?0:1;if($serial<$minimum||$serial>2_958_465)fail('The workbook contains an invalid Excel date.',422,'statement_date_invalid');$origin=$date1904?'1904-01-01':'1899-12-30';return(new DateTimeImmutable($origin,new DateTimeZone('UTC')))->modify('+'.$serial.' days')->format('Y-m-d');}
    return parse_statement_date($value);
}

/** Parse actual OOXML bytes. Browser cells and cached formula results are never authoritative. */
function parse_xlsx_statement_v5990(string $path,?int &$excludedCount=null): array
{
    if(!class_exists('ZipArchive')||!class_exists('DOMDocument'))fail('XLSX statement import requires the PHP zip and XML extensions.',503,'statement_xlsx_unavailable');
    if((int)filesize($path)>10*1024*1024)fail('Statement workbooks are limited to 10 MB.',413,'statement_workbook_size');
    $zip=new ZipArchive();if($zip->open($path,ZipArchive::RDONLY)!==true)fail('Choose a valid, unencrypted .xlsx workbook.',422,'statement_workbook_invalid');
    try{
        if($zip->numFiles>250)fail('The workbook contains too many parts.',422,'statement_workbook_unsafe');$expanded=0;$names=[];
        for($i=0;$i<$zip->numFiles;$i++){$stat=$zip->statIndex($i);$name=(string)$stat['name'];$lower=strtolower($name);$expanded+=(int)$stat['size'];if($expanded>64_000_000||(int)$stat['size']>48_000_000||isset($names[$lower])||str_contains($name,'\\')||preg_match('~(?:^/|(?:^|/)\.\.(?:/|$)|\x00)~',$name)||preg_match('~(?:vba|macros|embeddings/|externalLinks/|connections\.xml|queryTables/|activeX/|calcChain\.xml)~i',$name))fail('Macros, formulas, external content, duplicate or unsafe workbook parts are not permitted.',422,'statement_workbook_unsafe');$names[$lower]=true;
            $bytes=(string)$zip->getFromIndex($i);if(str_ends_with($lower,'.rels'))foreach(tegh_statement_xml_v5990($bytes)->getElementsByTagNameNS('*','Relationship') as $rel)if(strtolower($rel->getAttribute('TargetMode'))==='external')fail('External workbook links are not permitted.',422,'statement_workbook_unsafe');
            if(preg_match('~^xl/worksheets/[^/]+\.xml$~i',$name)&&tegh_statement_xml_v5990($bytes)->getElementsByTagNameNS('*','f')->length)fail('Formula cells are not permitted in statement workbooks. Export values only.',422,'statement_workbook_formulas');
        }
        $workbook=(string)$zip->getFromName('xl/workbook.xml');$rels=(string)$zip->getFromName('xl/_rels/workbook.xml.rels');if($workbook===''||$rels==='')fail('Required workbook parts are missing.',422,'statement_workbook_invalid');
        $workbookDoc=tegh_statement_xml_v5990($workbook);$date1904=in_array(strtolower((string)($workbookDoc->getElementsByTagNameNS('*','workbookPr')->item(0)?->getAttribute('date1904')??'')),['1','true'],true);$sheets=[];
        foreach($workbookDoc->getElementsByTagNameNS('*','sheet') as $sheet){$sheets[]=['name'=>(string)$sheet->getAttribute('name'),'state'=>strtolower((string)$sheet->getAttribute('state')),'rid'=>(string)$sheet->getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id')];}
        $allowed=['transactions','summary','validation','source provenance','account suggestions'];foreach($sheets as $sheet)if(!in_array(strtolower($sheet['name']),$allowed,true))fail('Unexpected worksheet "'.$sheet['name'].'" is populated. Use one Transactions sheet plus optional Summary/Validation/provenance sheets.',422,'statement_workbook_sheets');
        $candidates=array_values(array_filter($sheets,static fn(array $s):bool=>strtolower($s['name'])==='transactions'&&$s['state']!=='hidden'&&$s['state']!=='veryhidden'));if(count($candidates)!==1)fail('The workbook must contain one visible worksheet named Transactions.',422,'statement_workbook_sheets');$rid=$candidates[0]['rid'];
        $target='';foreach(tegh_statement_xml_v5990($rels)->getElementsByTagNameNS('*','Relationship') as $rel)if($rel->getAttribute('Id')===$rid)$target=(string)$rel->getAttribute('Target');if(!preg_match('~^(?:/xl/)?worksheets/[A-Za-z0-9_.-]+\.xml$~D',$target))fail('The Transactions worksheet relationship is invalid.',422,'statement_workbook_invalid');$target=str_starts_with($target,'/xl/')?ltrim($target,'/'):'xl/'.$target;
        $strings=[];$shared=$zip->getFromName('xl/sharedStrings.xml');if($shared!==false){foreach(tegh_statement_xml_v5990((string)$shared)->getElementsByTagNameNS('*','si') as $si){$text='';foreach($si->getElementsByTagNameNS('*','t') as $node)$text.=$node->textContent;$strings[]=$text;if(count($strings)>100_000)fail('The workbook contains too many shared strings.',413,'statement_workbook_size');}}
        $sheetXml=$zip->getFromName($target);if($sheetXml===false)fail('The Transactions worksheet is missing.',422,'statement_workbook_invalid');$sheetDoc=tegh_statement_xml_v5990((string)$sheetXml);$matrix=[];
        foreach($sheetDoc->getElementsByTagNameNS('*','row') as $row){$rowNo=(int)$row->getAttribute('r');if($rowNo<1||isset($matrix[$rowNo]))fail('The workbook contains duplicate or invalid rows.',422,'statement_workbook_invalid');$cells=[];
            foreach($row->getElementsByTagNameNS('*','c') as $cell){if(!preg_match('/^([A-Z]{1,3})([1-9][0-9]*)$/D',(string)$cell->getAttribute('r'),$m)||(int)$m[2]!==$rowNo)fail('The workbook contains a misplaced cell.',422,'statement_workbook_invalid');$column=tegh_statement_xlsx_column_v5990($m[1]);if($column>63||isset($cells[$column]))fail('The Transactions worksheet exceeds the supported 64 columns.',422,'statement_workbook_columns');$type=(string)$cell->getAttribute('t');$value=(string)($cell->getElementsByTagNameNS('*','v')->item(0)?->textContent??'');if($type==='s'){if(!ctype_digit($value)||!isset($strings[(int)$value]))fail('The workbook contains an invalid shared string.',422,'statement_workbook_invalid');$value=$strings[(int)$value];}elseif($type==='inlineStr'){$value='';foreach($cell->getElementsByTagNameNS('*','t') as $node)$value.=$node->textContent;}elseif(!in_array($type,['','n','str','d'],true))fail('The workbook contains an unsupported cell value.',422,'statement_workbook_invalid');if(strlen($value)>60_000)fail('A workbook cell is too large.',413,'statement_workbook_size');$cells[$column]=$value;}
            if($cells!==[])$matrix[$rowNo]=$cells;
        }
        if(!isset($matrix[1]))fail('The Transactions worksheet has no header row.',422,'statement_workbook_headers');$headers=[];foreach($matrix[1] as $index=>$value)$headers[$index]=normalized_header($value);$date=find_header_index($headers,['date','transactiondate','posteddate','postingdate']);$description=find_header_index($headers,['description','memo','details','payee','name','transactiondescription']);$reference=find_header_index($headers,['reference','ref','transactionreference','chequenumber','checknumber']);$amount=find_header_index($headers,['amount','transactionamount','value']);$out=find_header_index($headers,['moneyout','debit','withdrawal','withdrawals']);$in=find_header_index($headers,['moneyin','credit','deposit','deposits']);$balance=find_header_index($headers,['runningbalance','balance']);$currency=find_header_index($headers,['currency','currencycode']);
        if($date===null||$description===null||($amount===null&&$out===null&&$in===null))fail('Transactions headers must include Date, Description, and Amount or Money Out/Money In.',422,'statement_workbook_headers');$rows=[];$excluded=0;
        foreach($matrix as $rowNo=>$cells){if($rowNo===1)continue;if(count($rows)>=5000)fail('A single import may contain at most 5,000 transactions.',413,'statement_row_limit');$get=static fn(?int $index):string=>$index===null?'':trim((string)($cells[$index]??''));$desc=preg_replace('/\s+/u',' ',$get($description))??'';$signed=$get($amount);$debit=$get($out);$credit=$get($in);$fromSigned=$signed!==''?parse_statement_amount($signed,true):0;$fromSplit=($debit!==''?-abs(parse_statement_amount($debit,true)):0)+($credit!==''?abs(parse_statement_amount($credit,true)):0);if($debit!==''&&$credit!==''&&$fromSplit!==0&&parse_statement_amount($debit,true)!==0&&parse_statement_amount($credit,true)!==0)fail('Transactions row '.$rowNo.' contains both Money Out and Money In.',422,'statement_amount_conflict');if($signed!==''&&($debit!==''||$credit!=='')&&$fromSigned!==$fromSplit)fail('Transactions row '.$rowNo.' has conflicting amount representations.',422,'statement_amount_conflict');$cents=$signed!==''?$fromSigned:$fromSplit;if($cents===0||is_statement_non_transaction_row($desc)){$excluded++;continue;}if($desc==='')fail('Transactions row '.$rowNo.' has a non-zero amount but no description.',422,'statement_description_required');$rowDate=tegh_statement_xlsx_date_v5990($get($date),$date1904);assert_not_future_date($rowDate,'Statement transaction date');$rowCurrency=strtoupper($get($currency));if($rowCurrency!==''&&!preg_match('/^[A-Z]{3}$/D',$rowCurrency))fail('Transactions row '.$rowNo.' has an invalid Currency.',422,'statement_currency_invalid');$item=['date'=>$rowDate,'reference'=>optional_text($get($reference),120),'currency'=>$rowCurrency?:null,'amountCents'=>$cents,'sourceRow'=>$rowNo]+statement_description_fields($desc,'Description in Transactions row '.$rowNo);if($get($balance)!=='')$item['sourceRunningBalanceCents']=parse_statement_amount($get($balance),true);$rows[]=$item;}
        if(!$rows)fail('No transaction rows were found in the Transactions worksheet.',422,'statement_workbook_empty');$excludedCount=$excluded;return $rows;
    }finally{$zip->close();}
}
