import {S,sql,rec,check,save,need,ORIGIN} from './lib.mjs';import fs from 'fs';
const key=fs.readFileSync(process.env.GATE_SETUP_KEY_FILE,'utf8').trim();
const A='H-INST';const s=new S();
let r=await s.call('health',{company:false});rec('H-01',A,'GET /api/health over HTTPS before install',r.s===200?'PASS':'FAIL',r.s+' '+JSON.stringify(r.b).slice(0,200));
r=await s.call('auth/me',{company:false});rec('H-02',A,'auth/me on empty DB reports setup required',(JSON.stringify(r.b).includes('setup'))?'PASS':'FAIL',r.s+' '+JSON.stringify(r.b).slice(0,200));
r=await s.call('auth/setup',{method:'POST',json:{setupKey:'wrong-key-xxxxxxxxxxxxxxxxxxxxxxxx',email:'owner@gate.test',displayName:'Gate Owner',password:'Gate!Owner#2026pw'},company:false});
check('H-03',A,'Setup with wrong key refused 403',r.s,403);
r=await s.call('auth/setup',{method:'POST',json:{setupKey:key,email:'owner@gate.test',displayName:'Gate Owner',password:'Gate!Owner#2026pw'},company:false,origin:'https://evil.example'});
check('H-04',A,'Setup from foreign Origin refused',r.s>=400,true);
r=await s.call('auth/setup',{method:'POST',json:{setupKey:key,email:'owner@gate.test',displayName:'Gate Owner',password:'Gate!Owner#2026pw'},company:false});
check('H-05',A,'Fresh install: owner setup succeeds (201) and schema created',r.s,201);
const tables=+sql("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='tegh_gate'");
rec('H-06',A,'Schema tables created on fresh DB',tables>50?'PASS':'FAIL',tables+' tables');
r=await s.call('auth/setup',{method:'POST',json:{setupKey:key,email:'x@gate.test',displayName:'Second',password:'Gate!Owner#2026pw'},company:false});
check('H-07',A,'Second setup locked (409)',r.s,409);
const s2=new S();await s2.login('owner@gate.test','Gate!Owner#2026pw');
r=await s2.call('auth/me',{company:false});
check('H-08',A,'Login over HTTPS; version/build/schema',[r.b.version,r.b.build,r.b.schemaVersion].map(String),['5.9.9','5990','46']);
const sc=(await new S().call('auth/login',{method:'POST',json:{email:'owner@gate.test',password:'Gate!Owner#2026pw'},company:false,raw:true})).headers.getSetCookie().join(' | ');
rec('H-09',A,'Session cookie flags Secure, HttpOnly, SameSite',/Secure/i.test(sc)&&/HttpOnly/i.test(sc)&&/SameSite/i.test(sc)?'PASS':'FAIL',sc.replace(/=[^;|]{8,}/g,'=<redacted>'));
r=await s2.call('startup/status',{company:false});rec('H-10',A,'startup/status after install',r.s===200?'PASS':'FAIL',r.s+' '+JSON.stringify(r.b).slice(0,300));
r=await s2.call('startup/migrate',{method:'POST',json:{backupConfirmed:true},company:false});
rec('H-11',A,'Fresh install: protected database upgrade (Schema 43 → 46) completes from the owner session',r.s===200&&r.b?.schemaVersion===46?'PASS':'FAIL',r.s+' steps '+(r.b?.steps||[]).map(x=>x.id+':'+x.state).join(','));
r=await s2.call('startup/status',{company:false});rec('H-12',A,'After upgrade: startup status Schema 46, not degraded',r.b?.schemaVersion===46&&r.b?.degraded===false?'PASS':'FAIL',JSON.stringify({s:r.b?.schemaVersion,d:r.b?.degraded,w:r.b?.warningCode}));
save('install.json');
