// R145: PDF statement converter. Six synthetic statements (fictional banks/people/amounts, conv/make-fixtures.mjs)
// copy three common Canadian layouts plus an ISO-date layout, a statement with a missing line, and a statement with
// no column headings. Expected figures come from the generator's own integer-cent arithmetic, not from Tegh code.
import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';import fs from 'fs';import {S,sql,rec,check,save,need} from './lib.mjs';
const A='R145';const FX='/srv/gate/t/conv/fx';const X=JSON.parse(fs.readFileSync(FX+'/expected.json'));
const o=new S();await o.login('owner@gate.test','Gate!Owner#2026pw');
const co=need('co',await o.call('companies',{method:'POST',company:false,json:{name:'R145 Statements Inc',province:'ON',country:'Canada',businessType:'corporation',currency:'CAD',accountingBasis:'accrual',moduleMode:'accounting',fiscalYearEnd:'12-31',booksStartDate:'2025-01-01',taxRegistered:true,taxNumber:'123456789RT0001',coaMode:'default'}}));
const CID=co.company.id;const ids=JSON.parse(fs.readFileSync('/srv/gate/t/ids.json'));ids.R145=CID;fs.writeFileSync('/srv/gate/t/ids.json',JSON.stringify(ids));
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',args:['--no-proxy-server','--host-resolver-rules=MAP gate.test 127.0.0.1']});
const p=await (await b.newContext({viewport:{width:1440,height:900},ignoreHTTPSErrors:true})).newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message.slice(0,160)));
await p.goto('https://gate.test/app.html');await p.fill('#sr-login-form input[name=email]','owner@gate.test');await p.fill('#sr-login-form input[name=password]','Gate!Owner#2026pw');await p.click('#sr-login-form button[type=submit]');
await p.waitForFunction(()=>window.TeghPortal&&document.querySelector('.sidebar,.topbar'),null,{timeout:40000});
await p.evaluate(id=>{localStorage.setItem('sr-accountax-company',id);localStorage.setItem('sr-accountax-companies',JSON.stringify([id]))},CID);await p.goto('https://gate.test/app.html');await p.waitForFunction(()=>window.TeghPortal&&document.querySelector('.sidebar,.topbar'),null,{timeout:40000});
const t=async(id,title,fn)=>{try{const r=await fn();rec(id,A,title,r.ok?'PASS':'FAIL',r.info||'')}catch(e){rec(id,A,title,'FAIL',e.message.split('\n')[0].slice(0,200))}};
// --- Engine: run the shipped converter module in the browser on each fixture.
const run=async(k,accountType='')=>p.evaluate(async({b64,accountType})=>{const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));const file=new File([bytes],'s.pdf',{type:'application/pdf'});
  if(globalThis.TeghLoadFeature)await globalThis.TeghLoadFeature('ocr');else await import('/assets/tegh-native-ocr-v5220.js');
  const pd=await globalThis.TeghNativeOCR.extractStatementPages(file,{onPassword:()=>null,onProgress:()=>{}});const m=await import('/assets/tegh-bank-converter-v5990.js?v=5990-r145-tegh');
  const parsed=m.convertPages(pd.pages,{layout:'auto',dateOrder:'auto',accountType});const c=v=>Math.round(v*100);let ext=null;
  try{const copy={...parsed,rows:parsed.rows.map(r=>({...r}))};ext=m.reviewedExtraction(copy,{},pd.pageCount)}catch(e){ext={error:e.message}}
  return {rows:parsed.rows.map(r=>({date:r.date,desc:r.description,cents:c(r.amount),manual:!!r.needsManualAmount,issues:r.issues,method:r.extractionMethod})),check:parsed.layoutCheck||null,text:m.balanceCheckText(parsed.layoutCheck),
    ext:ext&&{error:ext.error,opening:ext.openingBalanceCents,closing:ext.closingBalanceCents,first:ext.firstTransactionDate,last:ext.lastTransactionDate,n:ext.rows?.length}}},{b64:fs.readFileSync(`${FX}/${k}.pdf`).toString('base64'),accountType});
const sum=(rows,f)=>rows.filter(f).reduce((s,r)=>s+r.cents,0);
for(const [k,type] of [['A',''],['B','credit_card'],['C',''],['E','']]){const e=X[k],r=await run(k,type);const dates=r.rows.map(x=>x.date).sort();
  check(`CV-${k}1`,A,`Statement ${k}: every row read with an amount and a date (${e.rows} rows, none needing manual entry)`,[r.rows.length,r.rows.filter(x=>x.manual||!x.date).length],[e.rows,0]);
  check(`CV-${k}2`,A,`Statement ${k}: net, money out and money in match the statement`,[sum(r.rows,()=>true),-sum(r.rows,x=>x.cents<0),sum(r.rows,x=>x.cents>0)],[e.netCents,e.outCents??-sum(r.rows,x=>x.cents<0),e.inCents??sum(r.rows,x=>x.cents>0)]);
  check(`CV-${k}3`,A,`Statement ${k}: opening and closing balances read and the rows balance to them`,[Math.round(r.check?.openingBalance*100),Math.round(r.check?.closingBalance*100),r.check?.balanced,r.check?.isCard],[e.openingCents,e.closingCents,true,e.card]);
  check(`CV-${k}4`,A,`Statement ${k}: first and last dates (years from the statement period) and the reviewed hand-off`,[dates[0],dates.at(-1),r.ext?.error??null,r.ext?.n,r.ext?.opening,r.ext?.closing],[e.first,e.last,null,e.rows,e.openingCents,e.closingCents]);
  rec(`CV-${k}5`,A,`Statement ${k}: the review screen says the balances agree`,/✓/.test(r.text)&&!/do not add up/.test(r.text)?'PASS':'FAIL',r.text.replace(/\$[\d,.]+/g,'$…'));
  if(k==='A')check('CV-A6',A,'Statement A: wrapped description lines are joined to their transaction, and the side panel is ignored',[r.rows.filter(x=>x.desc.includes(' · ')).length,r.rows.some(x=>/Need help|Overdraft|5,000/.test(x.desc))],[e.wrapped,false]);
  if(k==='B')check('CV-B6',A,'Card statement: December rows get 2025 and January rows 2026; payments are money in, charges money out; the payment slip after "Continued" is not a row',[r.rows.find(x=>/FIELDSTONE/.test(x.desc))?.date,r.rows.filter(x=>/PAYMENT - THANK YOU/.test(x.desc)).map(x=>x.cents>0),r.rows.some(x=>/MINIMUM|NEW BALANCE|Sub-total/i.test(x.desc))],['2025-12-30',[true,true,true],false]);
  if(k==='C')check('CV-C6',A,'Chequing statement: all page totals (Debits/Credits count and amount) agree; balance-forward lines and the footer note are not rows',[r.check?.pageChecks?.length,r.check?.pageChecks?.every(x=>x.ok),r.rows.some(x=>/BALANCE FORWARD|CHQ ENCLOSED/.test(x.desc))],[e.pageChecks,true,false]);
}
{const r=await run('D');check('CV-D1',A,'Statement with a missing line: still read, but flagged as not balancing, with the running-balance difference marked on the row',[r.rows.length,r.check?.balanced,r.check?.balanceMismatches>=1,r.rows.some(x=>/running balance/.test(x.issues)),/do not add up/.test(r.text)],[X.D.rows,false,true,true,true])}
{const r=await run('F');check('CV-F1',A,'Statement with no column headings: the column reader steps aside and the general reader still reads it',[r.rows.length,r.check,sum(r.rows,x=>!x.manual),r.rows.map(x=>x.date).sort()[0]],[X.F.rows,null,X.F.netCents,X.F.first])}
{const r=await run('B','bank');rec('CV-B7',A,'Card statement read into a bank account: the review warns that a credit card account may be the right one',/looks like a credit card statement/.test(r.text)?'PASS':'FAIL',r.text.slice(0,120))}
// --- Screen: Banking › Upload Statement › Bank Statement Converter, real file input, review dialog, hand-off to the server preview.
const card=sql(`SELECT id FROM bank_accounts WHERE company_id='${CID}' AND account_type='credit_card' LIMIT 1`),chq=sql(`SELECT id FROM bank_accounts WHERE company_id='${CID}' AND account_type='bank' LIMIT 1`);
const convert=async(k,bankId)=>{await p.evaluate(()=>TeghPortal.invokeMenuAction('Banking','Upload Statement'));const f=p.locator('[data-converter-form]').last();await f.waitFor({timeout:20000});
  await f.locator('select[name=bankAccountId]').selectOption(bankId);await f.locator('input[type=file]').setInputFiles(`${FX}/${k}.pdf`);await f.locator('button[type=submit]').click();
  const dlg=p.locator('.tegh-converter-panel');await dlg.locator('[data-converter-row]').first().waitFor({timeout:30000});return dlg};
await t('CV-UI1','Converter screen: statement A shows a green "balances agree" check, 12 rows and nothing needing correction',async()=>{const d=await convert('A',chq);const c=d.locator('[data-converter-balance-check]');const st=await d.locator('[data-converter-status]').textContent();await p.screenshot({path:'/srv/gate/ev/shots/r145-ui1-review.png'});
  return {ok:await c.getAttribute('data-state')==='ok'&&/✓/.test(await c.textContent())&&/^12 dated rows/.test(st)&&!/need an amount/.test(st)&&await d.locator('[data-converter-row]').count()===12,info:st}});
await t('CV-UI2','Confirming the review hands the rows and the statement balances to the server preview, which shows no difference',async()=>{const d=p.locator('.tegh-converter-panel');await d.locator('[data-reviewed-confirm]').check();await d.locator('[data-converter-continue]').click();
  const res=p.locator('[data-converter-result]').last();await res.waitFor({state:'visible',timeout:15000});const sumTxt=await res.locator('[data-converter-summary]').textContent();await res.locator('[data-converter-use]').click();
  let row='';for(let i=0;i<40&&!row;i++){await p.waitForTimeout(500);row=sql(`SELECT CONCAT(row_count,'|',opening_balance_cents,'|',closing_balance_cents) FROM statement_previews WHERE company_id='${CID}' ORDER BY created_at DESC LIMIT 1`)}
  const [n,op,cl]=row.split('|').map(Number);await p.screenshot({path:'/srv/gate/ev/shots/r145-ui2-preview.png'});
  return {ok:/12 reviewed rows/.test(sumTxt)&&n===12&&op===X.A.openingCents&&cl===X.A.closingCents&&cl-op===X.A.netCents,info:`${sumTxt.trim()} | preview ${n} rows, opening ${op}, closing ${cl}`}});
await t('CV-UI3','Converter screen: the card statement into the credit card account balances (owed amounts shown as owed)',async()=>{await p.keyboard.press('Escape');await p.waitForTimeout(800);const d=await convert('B',card);const c=d.locator('[data-converter-balance-check]');const txt=await c.textContent();await p.screenshot({path:'/srv/gate/ev/shots/r145-ui3-card.png'});
  return {ok:await c.getAttribute('data-state')==='ok'&&/Balance owed \$2,450\.00/.test(txt)&&/new balance owed of \$1,851\.33/.test(txt),info:txt}});
await t('CV-UI4','Converter screen: the statement with a missing line shows an amber "do not add up" check and marks the row',async()=>{await d0close();const d=await convert('D',chq);const c=d.locator('[data-converter-balance-check]');const txt=await c.textContent();await p.screenshot({path:'/srv/gate/ev/shots/r145-ui4-mismatch.png'});
  return {ok:await c.getAttribute('data-state')==='warn'&&/do not add up/.test(txt)&&await d.locator('[data-converter-row]',{hasText:'running balance'}).count()>=1,info:txt.slice(0,160)}});
async function d0close(){const x=p.locator('.tegh-converter-panel [data-converter-cancel]').first();if(await x.count())await x.click();await p.waitForTimeout(600)}
await d0close();
// --- Document Intake: local field reading on synthetic bills/receipts (text PDFs, a scanned PDF, phone-style photos).
const DX='/srv/gate/t/conv/dx';const DXE=JSON.parse(fs.readFileSync(DX+'/expected.json'));
fs.copyFileSync('/srv/gate/t/conv/ocr-r144.js','/srv/gate/www/assets/zz-ocr-r144-compare.js');
const extractAll=async src=>{const q=await p.context().newPage();await q.goto('https://gate.test/404.html');await q.addScriptTag({url:src});const out={};
  for(const k of Object.keys(DXE)){const f=`${DX}/${k}.${DXE[k].kind==='png'?'png':'pdf'}`;out[k]=await q.evaluate(async({b64,type})=>{const bytes=Uint8Array.from(atob(b64),c=>c.charCodeAt(0));try{const r=await window.TeghNativeOCR.extract(new File([bytes],'d',{type}));return {method:r.extractionMethod,c:r.candidate}}catch(e){return {method:'error: '+String(e.message).slice(0,90),c:{}}}},{b64:fs.readFileSync(f).toString('base64'),type:DXE[k].kind==='png'?'image/png':'application/pdf'})}
  await q.close();return out};
const fieldScore=(k,c)=>Object.entries(DXE[k].want).map(([f,v])=>{const got=f==='lineItems'?(c.lineItems||[]).length:f==='alternatives'?(c.alternatives||[]).map(a=>a.documentDate):c[f]??'';return {f,ok:v&&v.re?new RegExp(v.re).test(got):JSON.stringify(got)===JSON.stringify(v),got}});
const NEW=await extractAll('/assets/tegh-native-ocr-v5220.js?v=5990-r145-tegh'),OLD=await extractAll('/assets/zz-ocr-r144-compare.js');fs.unlinkSync('/srv/gate/www/assets/zz-ocr-r144-compare.js');
const titles={I1:'text PDF invoice (two-column header, line items, HST, Net 30)',I2:'French (Québec) invoice: TPS + TVQ, "185,69 $" amounts, "15 mars 2026"',I3:'phone-style receipt photo with a date that reads both ways (03/04/2026)',I4:'scanned (image-only) PDF invoice: GST + PST, "Mar 20, 2026", Net 15',I5:'fuel receipt photo with tax "included" in the total',I6:'tiny low-contrast café receipt photo',I7:'scanned bill that is mostly blank page (little text)'};
let newOk=0,oldOk=0,n=0;
for(const k of Object.keys(DXE)){const s=fieldScore(k,NEW[k].c),o=fieldScore(k,OLD[k].c);n+=s.length;newOk+=s.filter(x=>x.ok).length;oldOk+=o.filter(x=>x.ok).length;const bad=s.filter(x=>!x.ok);
  rec(`DI-${k}`,A,`Document Intake reads the ${titles[k]}: every field right`,bad.length?'FAIL':'PASS',`${NEW[k].method}; ${bad.length?'misses '+bad.map(x=>x.f+'='+JSON.stringify(x.got)).join(', '):s.map(x=>x.f).join(', ')} | R144 reader: ${o.filter(x=>x.ok).length}/${o.length}${/error/.test(OLD[k].method)?' ('+OLD[k].method+')':''}`)}
rec('DI-CMP',A,'Field accuracy across the six documents, R145 reader vs the R144 reader (for information)','INFO',`R145 ${newOk}/${n} fields; R144 ${oldOk}/${n} fields`);
check('DI-AMB',A,'An ambiguous numeric date is never guessed: the date stays empty and both readings are offered',[NEW.I3.c.documentDate,(NEW.I3.c.alternatives||[]).length,NEW.I3.c.confidenceBps<=6000],['',2,true]);
check('DI-SCAN',A,'Scanned PDFs are read by OCR in this browser (the bundled PDF reader no longer needs Map.getOrInsertComputed)',[NEW.I4.method,/getOrInsertComputed/.test(OLD.I4.method)],['ocr',true]);
// Screen: Payables › Document Intake, real upload, review form with the amount check and the date choices.
const intake=async()=>{await p.evaluate(()=>TeghPortal.invokeMenuAction('Payables','Document Intake'));await p.locator('[data-native-document-upload]').waitFor({timeout:20000})};
const upload=async f=>{const form=p.locator('[data-native-document-upload]');if(!await form.locator('button[type=submit]').isVisible()){await p.locator('summary:visible',{hasText:/^Upload document/}).first().click();await form.locator('button[type=submit]').waitFor({state:'visible',timeout:10000})}await form.locator('select[name=documentType]').selectOption('vendor_bill',{force:true});await form.locator('input[name=file]').setInputFiles(f);await form.locator('button[type=submit]').click()};
await t('DI-UI0','DEF-14: the Upload document panel shows a full-width "Upload and Extract Locally" button inside the panel',async()=>{await intake();await p.locator('summary:visible',{hasText:/^Upload document/}).first().click();const btn=p.locator('[data-native-document-upload] button[type=submit]');await btn.waitFor({state:'visible',timeout:10000});const r=await btn.boundingBox(),panel=await p.locator('[data-native-document-upload]').boundingBox();await p.screenshot({path:'/srv/gate/ev/shots/r145-intake-0-upload-panel.png'});await p.keyboard.press('Escape');
  return {ok:r.width>=200&&r.height<=60&&r.x+r.width<=panel.x+panel.width+1,info:`button ${Math.round(r.width)}×${Math.round(r.height)} at x ${Math.round(r.x)}, form right edge ${Math.round(panel.x+panel.width)}`}});
await t('DI-UI1','Document Intake screen: the uploaded invoice shows the read fields and "Subtotal + tax = total ✓"',async()=>{await intake();await upload(`${DX}/I1.pdf`);const card=p.locator('[data-native-document]').filter({has:p.locator('input[name=partyName][value="Northwind Office Supply Ltd."]')}).first();await card.waitFor({timeout:60000});
  const v=async n=>card.locator(`[name=${n}]`).inputValue();const chk=await card.locator('[data-amount-check]').textContent();await p.screenshot({path:'/srv/gate/ev/shots/r145-intake-1.png'});
  const got=[await v('documentNumber'),await v('documentDate'),await v('dueDate'),await v('subtotalCents'),await v('taxCents'),await v('totalCents'),chk];return {ok:JSON.stringify(got)===JSON.stringify(['INV-20418','2026-03-04','2026-04-03','359.00','46.67','405.67','Subtotal + tax = total ✓']),info:got.join(' | ')}});
await t('DI-UI2','Changing the tax so the amounts no longer add up shows the difference straight away',async()=>{const card=p.locator('[data-native-document]').filter({has:p.locator('input[name=partyName][value="Northwind Office Supply Ltd."]')}).first();await card.locator('[name=taxCents]').fill('50.00');const chk=await card.locator('[data-amount-check]');const txt=await chk.textContent();return {ok:await chk.getAttribute('data-state')==='warn'&&/more than the total by 3\.33/.test(txt),info:txt}});
await t('DI-UI3','A receipt photo with 03/04/2026 offers "March 4, 2026" and "April 3, 2026"; choosing one fills the date and the review saves as ready',async()=>{await intake();await upload(`${DX}/I3.png`);const rb=p.locator('[data-r22-review-key]',{hasText:'I3.png'}).first();await rb.waitFor({timeout:90000});await rb.click();const card=p.locator('[data-native-document]').filter({has:p.locator('[data-date-choices]')}).first();await card.waitFor({timeout:90000});
  const labels=await card.locator('[data-date-choice]').allTextContents();await card.locator('[data-date-choice]',{hasText:'March 4, 2026'}).click();const d=await card.locator('[name=documentDate]').inputValue();await p.screenshot({path:'/srv/gate/ev/shots/r145-intake-3.png'});
  await card.locator('[name=verified]').check();await card.locator('button[type=submit]',{hasText:'Save Human Review'}).click();let st='';for(let i=0;i<30&&st!=='ready';i++){await p.waitForTimeout(500);st=sql(`SELECT state FROM native_agent_documents WHERE company_id='${CID}' AND JSON_UNQUOTE(JSON_EXTRACT(candidate_json,'$.documentNumber'))='0042-118' ORDER BY created_at DESC LIMIT 1`)}
  return {ok:JSON.stringify(labels)===JSON.stringify(['March 4, 2026','April 3, 2026'])&&d==='2026-03-04'&&st==='ready',info:`${labels.join(' / ')} → ${d}; state ${st}`}});
rec('CV-JS',A,'No JavaScript errors',errs.length?'FAIL':'PASS',errs.join(' | ').slice(0,300));
check('CV-NOPOST',A,'Nothing was imported, drafted or posted: no bank transactions, vendor invoices or journal entries in the test company',[sql(`SELECT COUNT(*) FROM bank_transactions WHERE company_id='${CID}'`),sql(`SELECT COUNT(*) FROM bills WHERE company_id='${CID}'`),sql(`SELECT COUNT(*) FROM journal_entries WHERE company_id='${CID}'`)],['0','0','0']);
await b.close();save('r145.json');
