// R148: sign-in screen with two tabs — Sign in, and Create account (through an invitation link). Real invitations are
// created through the API and their links read from the STARTTLS mail sandbox, as an invitee would receive them.
import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';import fs from 'fs';import {S,sql,rec,check,save,need,mails} from './lib.mjs';
const A='R148';const ids=JSON.parse(fs.readFileSync('/srv/gate/t/ids.json'));const CID=ids.R144||ids.BC;
// Earlier gate suites accept many invitations from this test machine; start with a clean 15-minute attempt window.
sql(`DELETE FROM invitation_attempts`);
const o=new S();await o.login('owner@gate.test','Gate!Owner#2026pw');o.cid=CID;
const invite=async(email,role='viewer')=>{const before=mails().length;const r=await o.call('platform/invitations',{method:'POST',json:{action:'create_account',email,scope:'company',assignments:[{companyId:CID,role}],operationKey:'r148-'+email.replace(/[^a-z0-9]/gi,'')+'-'+Date.now()}});
  const all=mails();const mail=all.length>before?all.at(-1):null;const token=mail?.t.match(/accountSetup=([A-Za-z0-9_-]+)/)?.[1];if(!token)throw new Error('no invitation link: '+r.s+' '+JSON.stringify(r.b).slice(0,200));return token};
const stamp=Date.now().toString(36);const newEmail=`newperson-${stamp}@gate.test`,pasteEmail=`pasted-${stamp}@gate.test`,pw='R148!Invitee#2026pw';
const tNew=await invite(newEmail),tPaste=await invite(pasteEmail),tExisting=await invite('viewer@gate.test','editor').catch(()=>null),tUsed=await invite(`used-${stamp}@gate.test`);
{const n=new S();const d=await n.call('platform/invite-details?token='+tUsed,{company:false});await n.call('platform/invite-accept',{method:'POST',company:false,json:{token:tUsed,password:pw,confirmPassword:pw,acceptTerms:true,termsVersion:d.b.invitation?.termsVersion,privacyVersion:d.b.invitation?.privacyVersion}});}
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',args:['--no-proxy-server','--host-resolver-rules=MAP gate.test 127.0.0.1']});
const errs=[];const fresh=async(w=1440,h=900)=>{const ctx=await b.newContext({viewport:{width:w,height:h},ignoreHTTPSErrors:true,isMobile:w<800,hasTouch:w<800});const p=await ctx.newPage();p.on('pageerror',e=>errs.push(e.message.slice(0,150)));return p};
const t=async(id,title,fn)=>{try{const r=await fn();rec(id,A,title,r.ok?'PASS':'FAIL',r.info||'')}catch(e){rec(id,A,title,'FAIL',e.message.split('\n')[0].slice(0,200))}};
const tabs=async p=>p.evaluate(()=>[...document.querySelectorAll('.sr-gate-choice [role=tab]')].filter(x=>!x.hidden&&x.getClientRects().length).map(x=>`${x.textContent.trim()}${x.getAttribute('aria-selected')==='true'?'*':''}`));
const visibleForm=async p=>p.evaluate(()=>[...document.querySelectorAll('.sr-gate-form')].filter(f=>!f.hidden&&f.getClientRects().length).map(f=>f.id).join(','));

await t('IN-01','Plain app.html: two tabs (Sign in selected, Create account) and the sign-in form',async()=>{const p=await fresh();await p.goto('https://gate.test/app.html?forceSignIn=1');await p.waitForSelector('#sr-login-form:not([hidden])');await p.waitForTimeout(800);const tb=await tabs(p),f=await visibleForm(p);await p.screenshot({path:'/srv/gate/ev/shots/r148-01-signin.png'});await p.close();return {ok:JSON.stringify(tb)==='["Sign in*","Create account"]'&&f==='sr-login-form',info:`${tb} | ${f}`}});
await t('IN-02','Create account tab without an invitation (invite-only beta): explanation, the email subject, and a paste box',async()=>{const p=await fresh();await p.goto('https://gate.test/app.html?forceSignIn=1');await p.waitForSelector('#sr-login-form:not([hidden])');await p.click('#sr-choose-register');await p.waitForSelector('#sr-invite-needed:not([hidden])');const tb=await tabs(p),txt=(await p.locator('#sr-invite-needed').textContent()).replace(/\s+/g,' ');await p.screenshot({path:'/srv/gate/ev/shots/r148-02-create-no-invite.png'});await p.close();
  return {ok:JSON.stringify(tb)==='["Sign in","Create account*"]'&&/invitation-only beta/.test(txt)&&/Set up your Tegh account/.test(txt)&&/Invitation link/.test(txt),info:`${tb} | ${txt.slice(0,120)}`}});
await t('IN-03','"Join Beta" (app.html?register=1) opens the Create account tab',async()=>{const p=await fresh();await p.goto('https://gate.test/app.html?register=1');await p.waitForSelector('#sr-invite-needed:not([hidden]), #sr-register-form:not([hidden])',{timeout:15000});const tb=await tabs(p),f=await visibleForm(p);await p.close();return {ok:tb.includes('Create account*')&&/sr-invite-needed|sr-register-form/.test(f),info:`${tb} | ${f}`}});
await t('IN-04','Invitation link opens Create account with both tabs, the invited email, company and role, and a name suggestion',async()=>{const p=await fresh();await p.goto(`https://gate.test/app.html#accountSetup=${tNew}`);await p.waitForSelector('#sr-invite-form:not([hidden])');await p.waitForFunction(()=>document.querySelector('#sr-invite-form [name=invitedEmail]').value);
  const tb=await tabs(p),email=await p.inputValue('#sr-invite-form [name=invitedEmail]'),co=await p.textContent('#sr-invite-companies'),name=await p.inputValue('#sr-invite-form [name=displayName]'),title=await p.textContent('#sr-invite-form [data-invite-title]'),hash=await p.evaluate(()=>location.hash);await p.screenshot({path:'/srv/gate/ev/shots/r148-04-invite.png'});
  globalThis.p4=p;return {ok:JSON.stringify(tb)==='["Sign in","Create account*"]'&&email===newEmail&&/Viewer/i.test(co)&&name.length>0&&/Create your account/.test(title)&&!/accountSetup/.test(hash),info:`${tb} | ${email} | ${co} | suggested "${name}" | url hash cleared ${!/accountSetup/.test(hash)}`}});
await t('IN-05','Switching to Sign in and back keeps the invitation (no second lookup needed)',async()=>{const p=globalThis.p4;await p.click('#sr-choose-login');await p.waitForSelector('#sr-login-form:not([hidden])');const mid=await visibleForm(p);await p.click('#sr-choose-register');await p.waitForSelector('#sr-invite-form:not([hidden])');const email=await p.inputValue('#sr-invite-form [name=invitedEmail]');return {ok:mid==='sr-login-form'&&email===newEmail,info:`${mid} → invite form for ${email}`}});
await t('IN-06','Keyboard: arrow keys move between the two tabs',async()=>{const p=globalThis.p4;await p.focus('#sr-choose-register');await p.keyboard.press('ArrowLeft');const a=await visibleForm(p),fa=await p.evaluate(()=>document.activeElement.id);await p.keyboard.press('ArrowRight');await p.waitForSelector('#sr-invite-form:not([hidden])');const bF=await visibleForm(p);return {ok:a==='sr-login-form'&&fa==='sr-choose-login'&&bF==='sr-invite-form',info:`${a} (${fa}) → ${bF}`}});
await t('IN-07','Creating the account with a typed name opens Tegh signed in; the name and company membership are stored',async()=>{const p=globalThis.p4;await p.fill('#sr-invite-form [name=displayName]','Priya Example-Test');await p.fill('#sr-invite-form [name=password]',pw);await p.fill('#sr-invite-form [name=confirm]',pw);await p.check('#sr-invite-form [name=acceptTerms]');await p.click('#sr-invite-form button[type=submit]');
  await p.waitForFunction(()=>window.TeghPortal&&document.querySelector('.sidebar,.topbar'),null,{timeout:60000});const u=sql(`SELECT CONCAT(display_name,'|',signup_source,'|',IF(terms_accepted_at IS NULL,'no-terms','terms')) FROM users WHERE email='${newEmail}'`);const m=sql(`SELECT cm.role FROM company_members cm JOIN users u ON u.id=cm.user_id WHERE u.email='${newEmail}' AND cm.company_id='${CID}'`);await p.screenshot({path:'/srv/gate/ev/shots/r148-07-signed-in.png'});await p.context().close();
  return {ok:u==='Priya Example-Test|invitation|terms'&&m==='viewer',info:`${u} | role ${m}`}});
await t('IN-08','A pasted invitation link (whole emailed URL) opens the invitation in the Create account tab',async()=>{const p=await fresh();await p.goto('https://gate.test/app.html?register=1');await p.waitForSelector('#sr-invite-needed:not([hidden])');await p.fill('#sr-invite-needed [name=inviteLink]',`https://books.sraccountax.ca/app.html#accountSetup=${tPaste}`);await p.click('#sr-invite-needed button[type=submit]');await p.waitForSelector('#sr-invite-form:not([hidden])');await p.waitForFunction(()=>document.querySelector('#sr-invite-form [name=invitedEmail]').value);const email=await p.inputValue('#sr-invite-form [name=invitedEmail]');await p.close();return {ok:email===pasteEmail,info:email}});
await t('IN-09','Pasting text that is not an invitation link gives a plain message and stays on the tab',async()=>{const p=await fresh();await p.goto('https://gate.test/app.html?register=1');await p.waitForSelector('#sr-invite-needed:not([hidden])');await p.fill('#sr-invite-needed [name=inviteLink]','hello');await p.click('#sr-invite-needed button[type=submit]');await p.waitForTimeout(600);const msg=(await p.textContent('#sr-invite-needed [data-invite-needed-message]')).replace(/\s+/g,' ');const f=await visibleForm(p);await p.close();return {ok:/doesn’t look like a Tegh invitation link/.test(msg)&&f==='sr-invite-needed',info:msg.slice(0,120)}});
await t('IN-10','An already-used invitation link shows "expired or already used" in the Create account tab, with Sign in available',async()=>{const p=await fresh();await p.goto(`https://gate.test/app.html#accountSetup=${tUsed}`);await p.waitForSelector('#sr-invite-needed:not([hidden])',{timeout:20000});const txt=(await p.textContent('#sr-invite-needed [data-invite-needed-message]')).trim();const tb=await tabs(p);await p.screenshot({path:'/srv/gate/ev/shots/r148-10-used-link.png'});await p.close();return {ok:/expired or has already been used/.test(txt)&&tb.includes('Sign in')&&tb.includes('Create account*'),info:`${txt} | ${tb}`}});
await t('IN-11','Invitation for someone who already has an account: "Accept your invitation" with current password only (no name, no confirm)',async()=>{if(!tExisting)return {ok:false,info:'invitation for the existing user could not be created'};const p=await fresh();await p.goto(`https://gate.test/app.html#accountSetup=${tExisting}`);await p.waitForSelector('#sr-invite-form:not([hidden])');await p.waitForFunction(()=>/Accept/.test(document.querySelector('#sr-invite-form [data-invite-title]').textContent));
  const vis=await p.evaluate(()=>({name:!document.querySelector('[data-invite-name]').hidden,confirm:!document.querySelector('[data-invite-confirm]').hidden,btn:document.querySelector('#sr-invite-form button[type=submit]').textContent,forgot:!document.querySelector('[data-invite-existing]').hidden}));await p.close();return {ok:!vis.name&&!vis.confirm&&/Accept invitation/.test(vis.btn)&&vis.forgot,info:JSON.stringify(vis)}});
await t('IN-12','Phone (390×844): both tabs and the invitation form fit without sideways scrolling',async()=>{const tok=await invite(`phone-${stamp}@gate.test`);const p=await fresh(390,844);await p.goto(`https://gate.test/app.html#accountSetup=${tok}`);await p.waitForSelector('#sr-invite-form:not([hidden])');await p.waitForTimeout(800);const m=await p.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth}));const tb=await tabs(p);await p.screenshot({path:'/srv/gate/ev/shots/r148-12-phone.png',fullPage:true});await p.close();return {ok:m.sw<=m.cw+1&&tb.length===2,info:`${JSON.stringify(m)} ${tb}`}});
check('IN-13',A,'Server: a name with < > is refused; an empty name falls back to the email-derived name',await (async()=>{const tk=await invite(`srv-${stamp}@gate.test`);const n=new S();const d=await n.call('platform/invite-details?token='+tk,{company:false});const base={token:tk,password:pw,confirmPassword:pw,acceptTerms:true,termsVersion:d.b.invitation?.termsVersion,privacyVersion:d.b.invitation?.privacyVersion};
  const bad=await n.call('platform/invite-accept',{method:'POST',company:false,json:{...base,displayName:'<script>'}});const ok=await n.call('platform/invite-accept',{method:'POST',company:false,json:{...base,displayName:''}});return [bad.s,ok.s,sql(`SELECT display_name FROM users WHERE email='srv-${stamp}@gate.test'`),d.b.invitation?.suggestedName]})(),[422,200,'Srv '+stamp[0].toUpperCase()+stamp.slice(1),'Srv '+stamp[0].toUpperCase()+stamp.slice(1)]);
rec('IN-JS',A,'No JavaScript errors',errs.length?'FAIL':'PASS',errs.join(' | ').slice(0,300));
await b.close();save('r148.json');
