// R149: account creation with an invitation code. Real invitations are created through the API and their codes read from
// the STARTTLS mail sandbox, exactly as an invitee receives them; the code is typed on the Create account tab with the email.
import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';import fs from 'fs';import {S,sql,rec,check,save,need,mails} from './lib.mjs';
const A='R149';const ids=JSON.parse(fs.readFileSync('/srv/gate/t/ids.json'));const CID=ids.R144||ids.BC;
// Earlier gate suites accept many invitations from this test machine; start with a clean 15-minute attempt window.
sql(`DELETE FROM invitation_attempts`);
// Test-only: earlier gate runs by the same owner count toward the 30-per-hour creation limit; age them so this run starts fresh.
sql(`UPDATE account_invitations SET created_at=created_at-INTERVAL 2 HOUR WHERE created_at>UTC_TIMESTAMP()-INTERVAL 2 HOUR`);
const o=new S();await o.login('owner@gate.test','Gate!Owner#2026pw');o.cid=CID;
const invite=async(email,role='viewer')=>{const before=mails().length;const r=await o.call('platform/invitations',{method:'POST',json:{action:'create_account',email,scope:'company',assignments:[{companyId:CID,role}],operationKey:'r149-'+email.replace(/[^a-z0-9]/gi,'')+'-'+Date.now()}});
  const mail=mails().slice(before).find(x=>x.t.includes(email));const code=mail?.t.match(/invitation code:\s*([A-Z0-9]{5}-[A-Z0-9]{5})/)?.[1];if(!code)throw new Error('no invitation code: '+r.s+' '+JSON.stringify(r.b).slice(0,200));return {email,code,mail:mail.t}};
const stamp=Date.now().toString(36);const pw='R149!Invitee#2026pw';
const iNew=await invite(`newperson-${stamp}@gate.test`),iSecond=await invite(`second-${stamp}@gate.test`),iUsed=await invite(`used-${stamp}@gate.test`),iExisting=await invite('viewer@gate.test','editor').catch(()=>null);
{const n=new S();const d=await n.call('platform/invite-details',{method:'POST',company:false,json:{email:iUsed.email,code:iUsed.code}});await n.call('platform/invite-accept',{method:'POST',company:false,json:{email:iUsed.email,code:iUsed.code,password:pw,confirmPassword:pw,acceptTerms:true,termsVersion:d.b.invitation?.termsVersion,privacyVersion:d.b.invitation?.privacyVersion}});}
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',args:['--no-proxy-server','--host-resolver-rules=MAP gate.test 127.0.0.1']});
const errs=[];const fresh=async(w=1440,h=900)=>{const ctx=await b.newContext({viewport:{width:w,height:h},ignoreHTTPSErrors:true,isMobile:w<800,hasTouch:w<800});const p=await ctx.newPage();p.on('pageerror',e=>errs.push(e.message.slice(0,150)));return p};
const t=async(id,title,fn)=>{try{const r=await fn();rec(id,A,title,r.ok?'PASS':'FAIL',r.info||'')}catch(e){rec(id,A,title,'FAIL',e.message.split('\n')[0].slice(0,200))}};
const tabs=async p=>p.evaluate(()=>[...document.querySelectorAll('.sr-gate-choice [role=tab]')].filter(x=>!x.hidden&&x.getClientRects().length).map(x=>`${x.textContent.trim()}${x.getAttribute('aria-selected')==='true'?'*':''}`));
const visibleForm=async p=>p.evaluate(()=>[...document.querySelectorAll('.sr-gate-form')].filter(f=>!f.hidden&&f.getClientRects().length).map(f=>f.id).join(','));
const createTab=async(p)=>{await p.goto('https://gate.test/app.html?register=1');await p.waitForSelector('#sr-invite-needed:not([hidden])',{timeout:20000})};
const enter=async(p,email,code)=>{await p.fill('#sr-invite-needed [name=inviteEmail]',email);await p.fill('#sr-invite-needed [name=inviteCode]','');await p.type('#sr-invite-needed [name=inviteCode]',code);await p.click('#sr-invite-needed button[type=submit]')};
const note=async p=>(await p.textContent('#sr-invite-needed [data-invite-needed-message]')).replace(/\s+/g,' ').trim();

check('IC-01',A,'The invitation email shows the code, the invited email and the Create account page, and carries no setup link or token',[!!iNew.code,iNew.mail.includes(iNew.email),/app\.html\?register=1/.test(iNew.mail),/accountSetup/.test(iNew.mail),/expires in 72 hours/.test(iNew.mail)],[true,true,true,false,true]);
await t('IC-02','Plain app.html: two tabs, Sign in selected',async()=>{const p=await fresh();await p.goto('https://gate.test/app.html?forceSignIn=1');await p.waitForSelector('#sr-login-form:not([hidden])');await p.waitForTimeout(600);const tb=await tabs(p);await p.screenshot({path:'/srv/gate/ev/shots/r149-01-signin.png'});await p.close();return {ok:JSON.stringify(tb)==='["Sign in*","Create account"]',info:String(tb)}});
await t('IC-03','Create account tab asks for the email address and the invitation code, and names the email to look for',async()=>{const p=await fresh();await p.goto('https://gate.test/app.html?forceSignIn=1');await p.waitForSelector('#sr-login-form:not([hidden])');await p.click('#sr-choose-register');await p.waitForSelector('#sr-invite-needed:not([hidden])');const txt=(await p.textContent('#sr-invite-needed')).replace(/\s+/g,' ');const fields=await p.locator('#sr-invite-needed input').evaluateAll(a=>a.map(i=>i.name));await p.screenshot({path:'/srv/gate/ev/shots/r149-02-create-tab.png'});await p.close();
  return {ok:JSON.stringify(fields)==='["inviteEmail","inviteCode"]'&&/Set up your Tegh account/.test(txt)&&/10-character invitation code/.test(txt),info:`${fields} | ${txt.slice(0,110)}`}});
await t('IC-04','"Join Beta" (app.html?register=1) opens the Create account tab',async()=>{const p=await fresh();await createTab(p);const tb=await tabs(p);await p.close();return {ok:tb.includes('Create account*'),info:String(tb)}});
await t('IC-05','The code is formatted as it is typed (lower case and spaces accepted)',async()=>{const p=await fresh();await createTab(p);await p.type('#sr-invite-needed [name=inviteCode]',iNew.code.replace('-',' ').toLowerCase());const v=await p.inputValue('#sr-invite-needed [name=inviteCode]');await p.close();return {ok:v===iNew.code,info:`typed "${iNew.code.replace('-',' ').toLowerCase()}" → "${v}"`}});
await t('IC-06','Email + code opens the account form: invited email, company and role, suggested name; both tabs still shown',async()=>{const p=await fresh();await createTab(p);await enter(p,iNew.email,iNew.code.toLowerCase());await p.waitForSelector('#sr-invite-form:not([hidden])');await p.waitForFunction(()=>document.querySelector('#sr-invite-form [name=invitedEmail]').value);
  const email=await p.inputValue('#sr-invite-form [name=invitedEmail]'),co=await p.textContent('#sr-invite-companies'),name=await p.inputValue('#sr-invite-form [name=displayName]'),tb=await tabs(p);await p.screenshot({path:'/srv/gate/ev/shots/r149-03-account-form.png'});globalThis.p6=p;
  return {ok:email===iNew.email&&/Viewer/.test(co)&&name.length>0&&JSON.stringify(tb)==='["Sign in","Create account*"]',info:`${email} | ${co} | "${name}" | ${tb}`}});
await t('IC-07','Switching to Sign in and back keeps the invitation; arrow keys move between the tabs',async()=>{const p=globalThis.p6;await p.click('#sr-choose-login');await p.waitForSelector('#sr-login-form:not([hidden])');await p.click('#sr-choose-register');await p.waitForSelector('#sr-invite-form:not([hidden])');const e1=await p.inputValue('#sr-invite-form [name=invitedEmail]');
  await p.focus('#sr-choose-register');await p.keyboard.press('ArrowLeft');const f1=await visibleForm(p);await p.keyboard.press('ArrowRight');await p.waitForSelector('#sr-invite-form:not([hidden])');return {ok:e1===iNew.email&&f1==='sr-login-form',info:`${e1} | ${f1}`}});
await t('IC-08','Creating the account with a typed name opens Tegh signed in; name, role and terms are stored',async()=>{const p=globalThis.p6;await p.fill('#sr-invite-form [name=displayName]','Priya Example-Test');await p.fill('#sr-invite-form [name=password]',pw);await p.fill('#sr-invite-form [name=confirm]',pw);await p.check('#sr-invite-form [name=acceptTerms]');await p.click('#sr-invite-form button[type=submit]');
  await p.waitForFunction(()=>window.TeghPortal&&document.querySelector('.sidebar,.topbar'),null,{timeout:60000});const u=sql(`SELECT CONCAT(display_name,'|',signup_source,'|',IF(terms_accepted_at IS NULL,'no-terms','terms')) FROM users WHERE email='${iNew.email}'`);const m=sql(`SELECT cm.role FROM company_members cm JOIN users u ON u.id=cm.user_id WHERE u.email='${iNew.email}' AND cm.company_id='${CID}'`);await p.context().close();
  return {ok:u==='Priya Example-Test|invitation|terms'&&m==='viewer',info:`${u} | role ${m}`}});
await t('IC-09','A wrong code is refused with a plain message; the tab stays open',async()=>{const p=await fresh();await createTab(p);await enter(p,iSecond.email,'K7M2Q-PX9RT');await p.waitForFunction(()=>document.querySelector('#sr-invite-needed [data-invite-needed-message]').dataset.state==='error',null,{timeout:15000});const n=await note(p),f=await visibleForm(p);await p.screenshot({path:'/srv/gate/ev/shots/r149-04-wrong-code.png'});await p.close();return {ok:/don’t match an open invitation/.test(n)&&f==='sr-invite-needed',info:n.slice(0,120)}});
await t('IC-10','The right code with a different email address is refused',async()=>{const p=await fresh();await createTab(p);await enter(p,`someone-else-${stamp}@gate.test`,iSecond.code);await p.waitForFunction(()=>document.querySelector('#sr-invite-needed [data-invite-needed-message]').dataset.state==='error',null,{timeout:15000});const n=await note(p);await p.close();return {ok:/don’t match an open invitation/.test(n),info:n.slice(0,100)}});
await t('IC-11','An already-used code is refused',async()=>{const p=await fresh();await createTab(p);await enter(p,iUsed.email,iUsed.code);await p.waitForFunction(()=>document.querySelector('#sr-invite-needed [data-invite-needed-message]').dataset.state==='error',null,{timeout:15000});const n=await note(p);await p.close();return {ok:/don’t match an open invitation/.test(n),info:n.slice(0,100)}});
await t('IC-12','A code with letters that are never used (O, I, L, 0, 1) is caught before sending',async()=>{const p=await fresh();await createTab(p);await enter(p,iSecond.email,'OOOOO-11111');await p.waitForTimeout(400);const n=await note(p);await p.close();return {ok:/never contains 0, 1, O, I or L/.test(n),info:n.slice(0,100)}});
await t('IC-13','Someone who already has an account: "Accept your invitation" with the current password only',async()=>{if(!iExisting)return {ok:false,info:'invitation for the existing user could not be created'};const p=await fresh();await createTab(p);await enter(p,iExisting.email,iExisting.code);await p.waitForSelector('#sr-invite-form:not([hidden])');await p.waitForFunction(()=>/Accept/.test(document.querySelector('#sr-invite-form [data-invite-title]').textContent));
  const vis=await p.evaluate(()=>({name:!document.querySelector('[data-invite-name]').hidden,confirm:!document.querySelector('[data-invite-confirm]').hidden,btn:document.querySelector('#sr-invite-form button[type=submit]').textContent}));await p.close();return {ok:!vis.name&&!vis.confirm&&/Accept invitation/.test(vis.btn),info:JSON.stringify(vis)}});
await t('IC-14','Phone (390×844): tabs, email and code fields, and the account form fit without sideways scrolling',async()=>{const i=await invite(`phone-${stamp}@gate.test`);const p=await fresh(390,844);await createTab(p);await p.screenshot({path:'/srv/gate/ev/shots/r149-05-phone-code.png',fullPage:true});await enter(p,i.email,i.code);await p.waitForSelector('#sr-invite-form:not([hidden])');await p.waitForTimeout(600);const m=await p.evaluate(()=>({sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth}));await p.screenshot({path:'/srv/gate/ev/shots/r149-06-phone-form.png',fullPage:true});await p.close();return {ok:m.sw<=m.cw+1,info:JSON.stringify(m)}});
check('IC-15',A,'Server: a name with < > is refused; an empty name falls back to the email-derived name (email + code)',await (async()=>{const i=await invite(`srv-${stamp}@gate.test`);const n=new S();const d=await n.call('platform/invite-details',{method:'POST',company:false,json:{email:i.email,code:i.code}});const base={email:i.email,code:i.code,password:pw,confirmPassword:pw,acceptTerms:true,termsVersion:d.b.invitation?.termsVersion,privacyVersion:d.b.invitation?.privacyVersion};
  const bad=await n.call('platform/invite-accept',{method:'POST',company:false,json:{...base,displayName:'<script>'}});const ok=await n.call('platform/invite-accept',{method:'POST',company:false,json:{...base,displayName:''}});return [bad.s,ok.s,sql(`SELECT display_name FROM users WHERE email='${i.email}'`)]})(),[422,200,'Srv '+stamp[0].toUpperCase()+stamp.slice(1)]);
check('IC-16',A,'Guessing is limited: after 10 tries for one email within 15 minutes the server answers 429, even for the right code',await (async()=>{const i=await invite(`limit-${stamp}@gate.test`);sql(`DELETE FROM invitation_attempts`);const n=new S();const codes=[];for(let k=0;k<10;k++){codes.push((await n.call('platform/invite-details',{method:'POST',company:false,json:{email:i.email,code:'K7M2Q-PX9R'+'23456789AB'[k]}})).s)}
  const right=await n.call('platform/invite-details',{method:'POST',company:false,json:{email:i.email,code:i.code}});sql(`DELETE FROM invitation_attempts`);return [codes.every(c=>c===410),right.s]})(),[true,429]);
check('IC-18',A,'Correct look-ups never use up the allowance (12 in a row all succeed), so one office can invite several people',await (async()=>{const i=await invite(`office-${stamp}@gate.test`);sql(`DELETE FROM invitation_attempts`);const n=new S();const out=[];for(let k=0;k<12;k++)out.push((await n.call('platform/invite-details',{method:'POST',company:false,json:{email:i.email,code:i.code}})).s);return out.every(x=>x===200)})(),true);
await t('IC-17','After too many tries the Create account tab says to wait 15 minutes',async()=>{const i=await invite(`limitui-${stamp}@gate.test`);sql(`DELETE FROM invitation_attempts`);const n=new S();for(let k=0;k<10;k++)await n.call('platform/invite-details',{method:'POST',company:false,json:{email:i.email,code:'K7M2Q-PX9R'+'23456789AB'[k]}});
  const p=await fresh();await createTab(p);await enter(p,i.email,i.code);await p.waitForFunction(()=>document.querySelector('#sr-invite-needed [data-invite-needed-message]').dataset.state==='error',null,{timeout:15000});const msg=await note(p);await p.close();sql(`DELETE FROM invitation_attempts`);return {ok:/Too many attempts\. Wait 15 minutes/.test(msg),info:msg}});
await t('IC-19','An invitation link sent before R149 (token after #) still opens the account form',async()=>{const i=await invite(`legacy-${stamp}@gate.test`);const {execFileSync}=await import('child_process');const tok=execFileSync('php',['/srv/gate/t/legacy-link.php',i.email],{encoding:'utf8'}).trim();
  const p=await fresh();await p.goto(`https://gate.test/app.html#accountSetup=${tok}`);await p.waitForSelector('#sr-invite-form:not([hidden])',{timeout:20000});await p.waitForFunction(()=>document.querySelector('#sr-invite-form [name=invitedEmail]').value);const e=await p.inputValue('#sr-invite-form [name=invitedEmail]');const tb=await tabs(p);await p.close();return {ok:e===i.email&&tb.includes('Create account*'),info:`${e} | ${tb}`}});
rec('IC-JS',A,'No JavaScript errors',errs.length?'FAIL':'PASS',errs.join(' | ').slice(0,300));
await b.close();save('r149.json');
