// R151 (browser): the shared document form, adding lines without the page jumping, editing from the registers on the
// main screen (no pop-up), and the sidebar. Results are checked in the database; figures are worked out by hand.
import {open} from './e2e/base.mjs';import {sql,rec,check,save} from './lib.mjs';
const A='R151UI';
const CID=sql("SELECT id FROM companies WHERE name LIKE 'R151 Documents Inc%' ORDER BY created_at DESC LIMIT 1");
if(!CID)throw new Error('run 19-r151.mjs first');
const acct=code=>sql(`SELECT id FROM accounts WHERE company_id='${CID}' AND code='${code}'`);
const jl=(type,id)=>sql(`SELECT CONCAT(a.code,':',SUM(l.debit_cents),'/',SUM(l.credit_cents)) FROM journal_entries e JOIN journal_lines l ON l.journal_entry_id=e.id JOIN accounts a ON a.id=l.account_id WHERE e.company_id='${CID}' AND e.source_type='${type}' AND e.source_id='${id}' GROUP BY a.code ORDER BY a.code`).split('\n').filter(Boolean);
const stamp=Date.now().toString(36);
const {b,p,errs}=await open(CID,{w:1440,h:900});
await p.evaluate(()=>{try{localStorage.removeItem('sr-sidebar-collapsed')}catch{}});
const shots='/srv/gate/ev/shots';
const t=async(id,title,fn)=>{try{const r=await fn();rec(id,A,title,r.ok?'PASS':'FAIL',r.info)}catch(e){rec(id,A,title,'FAIL',e.message.slice(0,300))}};
const editor=async(side,opts)=>{await p.evaluate(([s,o])=>TeghPortal.openDocumentEditor(s,o),[side,opts]);await p.waitForSelector('[data-r151-form]',{timeout:20000});await p.waitForTimeout(600)};
const row=i=>p.locator('tr[data-r151-line]').nth(i);
const fillRow=async(i,{desc,qty,rate,tax,gl})=>{const r=row(i);await r.locator('[name=description]').fill(desc);await r.locator('[name=qty]').fill(String(qty));await r.locator('[name=rate]').fill(String(rate));if(tax!==undefined)await r.locator('[name=taxKey]').selectOption(tax);if(gl)await r.locator('[name=accountId]').selectOption(gl)};
const scroller=()=>p.evaluate(()=>{let el=document.querySelector('[data-r151-form]');while(el&&el!==document.body){const s=getComputedStyle(el);if(/(auto|scroll)/.test(s.overflowY)&&el.scrollHeight>el.clientHeight)return el.className?'.'+[...el.classList].join('.'):el.tagName;el=el.parentElement}return 'document'});
const scrollTop=sel=>p.evaluate(s=>s==='document'?document.scrollingElement.scrollTop:document.querySelector(s).scrollTop,sel);
const setScroll=(sel,v)=>p.evaluate(([s,v])=>{const el=s==='document'?document.scrollingElement:document.querySelector(s);el.scrollTop=v},[sel,v]);
const ON=sql(`SELECT id FROM tax_codes WHERE company_id='${CID}' AND code='ON'`);
const CUST=sql(`SELECT id FROM customers WHERE company_id='${CID}' AND name='R151 Client Ltd'`),VEND=sql(`SELECT id FROM vendors WHERE company_id='${CID}' AND name='R151 Supplies Co'`);

await t('UI-01','One form: Document type offers Invoice, Credit note and Debit note (customer and vendor)',async()=>{await editor('customer',{kind:'invoice'});const c=await p.locator('[data-r151-type] option').allTextContents();await editor('vendor',{kind:'invoice'});const v=await p.locator('[data-r151-type] option').allTextContents();return {ok:c.join()==='Invoice,Credit note,Debit note'&&v.join()==='Vendor invoice,Supplier credit note,Supplier debit note',info:c.join('/')+' | '+v.join('/')}});
await t('UI-02','Layout: details on top, line grid below with Product/Service, Description, Qty, Rate, Tax, Amount, Total and GL account; no side summary',async()=>{await editor('customer',{kind:'invoice'});const h=(await p.locator('.r151-grid thead th').allTextContents()).map(x=>x.trim().toLowerCase()).filter(x=>x&&x!=='remove');const order=await p.evaluate(()=>{const f=document.querySelector('[data-r151-fields]').getBoundingClientRect(),g=document.querySelector('.r151-lines').getBoundingClientRect(),form=document.querySelector('[data-r151-form]').getBoundingClientRect();return{above:f.bottom<=g.top,gridWidth:Math.round(g.width/form.width*100),aside:!!document.querySelector('.r29-invoice-summary')}});await p.screenshot({path:shots+'/r151-01-invoice-form.png'});return {ok:h.join('|')==='#|product / service|description|qty|rate|tax|amount|total|gl account'&&order.above&&order.gridWidth>=95&&!order.aside,info:h.join('|')+' '+JSON.stringify(order)}});
await t('UI-03','Clicking “Add line” adds a row without the page jumping to the top',async()=>{await editor('customer',{kind:'invoice'});for(let i=0;i<5;i++)await p.click('[data-r151-add]');const sel=await scroller();await setScroll(sel,260);await p.waitForTimeout(200);const before=await scrollTop(sel);await p.click('[data-r151-add]');await p.waitForTimeout(400);const after=await scrollTop(sel);const rows=await p.locator('tr[data-r151-line]').count();return {ok:before>100&&after>=before-5&&rows===7,info:`scroller ${sel} before ${before} after ${after} rows ${rows}`}});
await t('UI-04','Removing a line and changing a line also keep the scroll position',async()=>{const sel=await scroller();const before=await scrollTop(sel);await row(3).locator('[data-r151-remove]').click();await row(2).locator('[name=qty]').fill('3');await p.waitForTimeout(300);const after=await scrollTop(sel);return {ok:Math.abs(after-before)<40&&before>100,info:`before ${before} after ${after}`}});
// Customer invoice through the form: Consulting 2 × $150 @ 4000 ON (HST 3900) + Training 1 × $80 @ 4100 no tax.
// Subtotal 38000, tax 3900, total 41900. GL: Dr 1200 41900 · Cr 4000 30000 · Cr 4100 8000 · Cr 2100 3900.
let invId='';
await t('UI-05','Customer invoice with two lines (different tax and GL) saves and issues; totals and GL match the lines',async()=>{await editor('customer',{kind:'invoice'});await p.selectOption('[name=partyId]',CUST);await fillRow(0,{desc:'Consulting',qty:2,rate:'150.00',tax:ON,gl:acct('4000')});await p.click('[data-r151-add]');await fillRow(1,{desc:'Training',qty:1,rate:'80.00',tax:'',gl:acct('4100')});
  const shown=(await p.locator('[data-r151-totals]').textContent()).replace(/\s+/g,' ');await p.click('[data-r151-save=post]');await p.waitForTimeout(3500);
  invId=sql(`SELECT id FROM invoices WHERE company_id='${CID}' AND total_cents=41900 ORDER BY created_at DESC LIMIT 1`);return {ok:!!invId&&/\$419\.00/.test(shown)&&JSON.stringify(jl('invoice',invId))===JSON.stringify(['1200:41900/0','2100:0/3900','4000:0/30000','4100:0/8000']),info:shown+' '+JSON.stringify(jl('invoice',invId))}});
// Vendor invoice: Rent 1 × $1,000 @ 6950 no tax + Cleaning 1 × $200 @ 6400 ON (2600). Total 122600.
let billId='';
await t('UI-06','Vendor invoice with two lines posts each line to its own GL account',async()=>{await editor('vendor',{kind:'invoice'});await p.selectOption('[name=partyId]',VEND);await p.fill('[name=number]','UI-VI-'+stamp);await fillRow(0,{desc:'Insurance premium',qty:1,rate:'1000.00',tax:'',gl:acct('6950')});await p.click('[data-r151-add]');await fillRow(1,{desc:'Cleaning',qty:1,rate:'200.00',tax:ON,gl:acct('6400')});
  await p.screenshot({path:shots+'/r151-02-vendor-invoice.png'});await p.click('[data-r151-save=post]');await p.waitForTimeout(3500);billId=sql(`SELECT id FROM bills WHERE company_id='${CID}' AND number='UI-VI-${stamp}'`);
  return {ok:!!billId&&JSON.stringify(jl('bill',billId))===JSON.stringify(['1100:2600/0','2050:0/122600','6400:20000/0','6950:100000/0']),info:JSON.stringify(jl('bill',billId))}});
await t('UI-07','Credit note: typing a number that is not in Tegh says so; saved against the customer with its own tax and GL',async()=>{await editor('customer',{kind:'credit'});await p.selectOption('[name=partyId]',CUST);await p.fill('[name=number]','PRE-2025-17-'+stamp);const hint=await p.locator('.r151-link').textContent();await fillRow(0,{desc:'Goodwill credit',qty:1,rate:'50.00',tax:ON,gl:acct('4000')});await p.click('[data-r151-save=post]');await p.waitForTimeout(3500);
  const n=sql(`SELECT CONCAT(status,'|',IFNULL(source_id,'none'),'|',foreign_total_cents) FROM accounting_notes WHERE company_id='${CID}' AND reference_number='PRE-2025-17-${stamp}'`);return {ok:/Not found in Tegh/.test(hint)&&n==='posted|none|5650',info:hint.trim().slice(0,90)+' | '+n}});
await t('UI-08','Credit note: typing an existing invoice number links it; tax follows the original; “Return items” fills its lines',async()=>{const num=sql(`SELECT number FROM invoices WHERE id='${invId}'`);await editor('customer',{kind:'credit'});await p.selectOption('[name=partyId]',CUST);await p.fill('[name=number]',num);await p.waitForTimeout(300);const hint=await p.locator('.r151-link').textContent();const ret=p.locator('[data-r151-return]');const vis=await ret.isVisible();await ret.click();await p.waitForTimeout(300);
  const rows=await p.locator('tr[data-r151-line]').count();const taxDisabled=await row(0).locator('[name=taxKey]').isDisabled();await p.screenshot({path:shots+'/r151-03-linked-credit.png'});return {ok:/Linked to/.test(hint)&&vis&&rows===2&&taxDisabled,info:`${hint.trim().slice(0,60)} rows ${rows} taxLocked ${taxDisabled}`}});
await t('UI-09','Switching the document type in the dropdown changes the form (vendor invoice number → original invoice number)',async()=>{await editor('vendor',{kind:'invoice'});const before=await p.locator('[data-r151-fields] label').allTextContents();await p.selectOption('[data-r151-type]','debit');await p.waitForTimeout(300);const after=await p.locator('[data-r151-fields] label').allTextContents();return {ok:before.some(x=>/Vendor invoice number/i.test(x))&&after.some(x=>/Original invoice number/i.test(x)),info:after.map(x=>x.trim().split('\n')[0]).join(' / ').slice(0,200)}});
// Draft → Edit from the register on the main screen.
await t('UI-10','Invoice register: the row Actions menu has Edit, which opens the draft on the main screen (no pop-up); changes are saved',async()=>{await editor('customer',{kind:'invoice'});await p.selectOption('[name=partyId]',CUST);await fillRow(0,{desc:'Draft item',qty:1,rate:'10.00',tax:'',gl:acct('4000')});await p.click('[data-r151-save=draft]');await p.waitForTimeout(3000);
  const draft=sql(`SELECT id FROM invoices WHERE company_id='${CID}' AND status='draft' ORDER BY created_at DESC LIMIT 1`),num=sql(`SELECT number FROM invoices WHERE id='${draft}'`);
  const grp=p.locator('aside.sidebar nav > button').filter({hasText:'Receivables'}).first();if(await grp.getAttribute('aria-expanded')!=='true'){await grp.click();await p.waitForTimeout(800)}await p.locator('aside.sidebar nav button').filter({hasText:/^Invoice Register$/}).first().click();await p.waitForSelector('button[aria-label^="Actions for"]',{timeout:20000});await p.waitForTimeout(800);const size=p.locator('select:visible').filter({has:p.locator('option[value="100"]')}).first();if(await size.count()){await size.selectOption('100');await p.waitForTimeout(1500)}await p.locator(`button[aria-label="Actions for ${num}"]`).first().click();await p.waitForTimeout(400);
  const items=(await p.locator('button:visible').allTextContents()).filter(x=>/Edit invoice|View invoice details/.test(x));await p.locator('button:visible',{hasText:'Edit invoice'}).first().click();await p.waitForSelector('[data-r151-form]',{timeout:15000});await p.waitForTimeout(800);
  const dialogs=await p.locator('dialog[open]').count();await row(0).locator('[name=rate]').fill('25.00');await p.click('[data-r151-save=draft]');await p.waitForTimeout(3000);const tot=sql(`SELECT total_cents FROM invoices WHERE id='${draft}'`);return {ok:dialogs===0&&tot==='2500',info:`menu ${items.join('/')} dialogs ${dialogs} total ${tot}`}});
await t('UI-11','Issued invoice: Edit opens on the main screen with amounts locked; the due date changes',async()=>{await p.evaluate(id=>TeghPortal.editInvoice(id),invId);await p.waitForSelector('[data-r151-form]',{timeout:15000});await p.waitForTimeout(800);const locked=await row(0).locator('[name=rate]').isDisabled();await p.fill('[name=dueDate]','2026-12-15');await p.click('[data-r151-save=details]');await p.waitForTimeout(3000);
  return {ok:locked&&sql(`SELECT CONCAT(due_date,'/',total_cents) FROM invoices WHERE id='${invId}'`)==='2026-12-15/41900',info:`locked ${locked} ${sql(`SELECT CONCAT(due_date,'/',total_cents) FROM invoices WHERE id='${invId}'`)}`}});
await t('UI-12','Invoice detail page: Edit opens the main-screen form, not a pop-up',async()=>{await p.evaluate(id=>TeghPortal.openInvoiceDetails(id),invId);await p.waitForSelector('[data-r20-edit]',{timeout:20000});await p.waitForTimeout(800);await p.click('[data-r20-edit]');await p.waitForSelector('[data-r151-form]',{timeout:15000});await p.waitForTimeout(500);const dialogs=await p.locator('dialog[open]').count();return {ok:dialogs===0,info:'open dialogs '+dialogs}});
await t('UI-13','Vendor register: Edit on an issued vendor invoice changes the memo only',async()=>{await p.evaluate(id=>TeghPortal.openDocumentEditor('vendor',{editId:id,editType:'bill'}),billId);await p.waitForSelector('[data-r151-form]',{timeout:15000});await p.waitForTimeout(600);const locked=await row(0).locator('[name=rate]').isDisabled();await p.fill('[name=message]','Paid by EFT');await p.click('[data-r151-save=details]');await p.waitForTimeout(3000);return {ok:locked&&sql(`SELECT CONCAT(memo,'/',total_cents) FROM bills WHERE id='${billId}'`)==='Paid by EFT/122600',info:sql(`SELECT CONCAT(memo,'/',total_cents) FROM bills WHERE id='${billId}'`)}});
await t('UI-14','Note register: a draft note has Edit, which opens it on the main screen',async()=>{await editor('customer',{kind:'credit'});await p.selectOption('[name=partyId]',CUST);await p.fill('[name=number]','DRAFT-REF-'+stamp);await fillRow(0,{desc:'Draft credit',qty:1,rate:'5.00',tax:'',gl:acct('4000')});await p.click('[data-r151-save=draft]');await p.waitForTimeout(3000);const id=sql(`SELECT id FROM accounting_notes WHERE company_id='${CID}' AND reference_number='DRAFT-REF-${stamp}'`);
  await p.locator(`[data-note-edit="${id}"]`).first().click();await p.waitForSelector('[data-r151-form]',{timeout:15000});await p.waitForTimeout(600);const val=await p.inputValue('[name=number]');await row(0).locator('[name=rate]').fill('7.00');await p.click('[data-r151-save=draft]');await p.waitForTimeout(3000);return {ok:val==='DRAFT-REF-'+stamp&&sql(`SELECT foreign_total_cents FROM accounting_notes WHERE id='${id}'`)==='700',info:val+' '+sql(`SELECT foreign_total_cents FROM accounting_notes WHERE id='${id}'`)}});
await t('UI-17','Vendor invoice: “Make this a recurring vendor invoice” still creates the schedule',async()=>{await editor('vendor',{kind:'invoice'});await p.selectOption('[name=partyId]',VEND);await p.fill('[name=number]','UI-REC-'+stamp);await fillRow(0,{desc:'Office rent',qty:1,rate:'900.00',tax:'',gl:acct('6950')});await p.check('[data-recurring-bill]');await p.fill('[data-recurring-name]','Rent '+stamp);await p.click('[data-r151-save=draft]');await p.waitForTimeout(3500);
  const prof=sql(`SELECT CONCAT(foreign_amount_cents,'/',(SELECT code FROM accounts WHERE id=category_account_id)) FROM recurring_bill_profiles WHERE company_id='${CID}' AND name='Rent ${stamp}'`);return {ok:prof==='90000/6950',info:'profile '+prof}});
await t('UI-18','Customer and product dropdowns still offer “add new” without leaving the form',async()=>{await editor('customer',{kind:'invoice'});const party=await p.locator('[name=partyId] option').allTextContents();const prod=await row(0).locator('[name=productServiceId] option').allTextContents();return {ok:party.some(x=>/Add New Customer/i.test(x))&&prod.some(x=>/Add Product or Service/i.test(x)),info:party.at(-1)+' | '+prod.at(-1)}});
await t('UI-15','Sidebar: right after choosing a menu item, the mouse wheel scrolls the menu by exactly the wheel amount (up and down)',async()=>{await p.setViewportSize({width:1366,height:480});await p.waitForTimeout(400);
  for(const g of ['Receivables','Payables']){const bt=p.locator('aside.sidebar nav > button').filter({hasText:g}).first();if(await bt.isVisible().catch(()=>false)&&await bt.getAttribute('aria-expanded')!=='true'){await bt.click();await p.waitForTimeout(500)}}
  await p.locator('aside.sidebar nav button').filter({hasText:/^Customers$/}).first().click();await p.waitForTimeout(150);
  const n=await p.evaluate(()=>{const n=document.querySelector('aside.sidebar nav');const r=n.getBoundingClientRect();return{top:n.scrollTop,max:n.scrollHeight-n.clientHeight,x:r.x+r.width/2,y:r.y+r.height/2}});
  await p.evaluate(()=>{const n=document.querySelector('aside.sidebar nav');n.style.scrollBehavior='auto';n.scrollTop=0;n.style.scrollBehavior=''});n.top=0;
  await p.mouse.move(n.x,n.y);await p.mouse.wheel(0,60);await p.waitForTimeout(400);const down=await p.evaluate(()=>document.querySelector('aside.sidebar nav').scrollTop);
  await p.mouse.wheel(0,-40);await p.waitForTimeout(400);const up=await p.evaluate(()=>document.querySelector('aside.sidebar nav').scrollTop);
  const wantDown=Math.min(n.max,n.top+60),wantUp=Math.max(0,wantDown-40);await p.setViewportSize({width:1440,height:900});
  return {ok:n.max>0&&Math.abs(down-wantDown)<=2&&Math.abs(up-wantUp)<=2,info:`max ${n.max} start ${n.top} → +60 → ${down} (want ${wantDown}) → −40 → ${up} (want ${wantUp})`}});
await b.close();
const ph=await open(CID,{w:390,h:844});
await t('UI-16','Phone (390×844): the form fits; the line grid scrolls sideways inside its own box',async()=>{await ph.p.evaluate(()=>TeghPortal.openDocumentEditor('customer',{kind:'invoice'}));await ph.p.waitForSelector('[data-r151-form]',{timeout:20000});await ph.p.waitForTimeout(800);const m=await ph.p.evaluate(()=>{const w=document.querySelector('.r151-grid-wrap');return{sw:document.documentElement.scrollWidth,cw:document.documentElement.clientWidth,grid:w.scrollWidth>w.clientWidth,ox:getComputedStyle(w).overflowX}});await ph.p.screenshot({path:shots+'/r151-04-phone.png'});return {ok:m.sw<=m.cw&&m.grid&&m.ox==='auto',info:JSON.stringify(m)}});
await ph.b.close();
rec('UI-JS',A,'No JavaScript errors',errs.length||ph.errs.length?'FAIL':'PASS',[...errs,...ph.errs].join(' | '));
save('r151ui.json');
