// R152: statement reader (Canadian EN/FR layouts, card statements, DR/CR, split amounts, two-line rows, PDFs holding
// several statements) and invoice reader (line items as a table, supplier memory, coding suggestions from history,
// duplicate checks, hand-off into the vendor invoice form). Fixtures are synthetic (fictional banks, suppliers and
// amounts) from conv/make-banks.mjs and conv/make-invoices.mjs; expected figures come from those generators' own
// integer-cent arithmetic, never from Tegh code.
import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';import fs from 'fs';import {execFileSync} from 'child_process';import {S,sql,rec,check,save,need} from './lib.mjs';
const A='R152';const FX='/srv/gate/t/conv/fx152',IX='/srv/gate/t/conv/ix152';
const XS=JSON.parse(fs.readFileSync(FX+'/expected.json')),XI=JSON.parse(fs.readFileSync(IX+'/expected.json')),X145=JSON.parse(fs.readFileSync('/srv/gate/t/conv/fx/expected.json'));
const o=new S();await o.login('owner@gate.test','Gate!Owner#2026pw');const stamp=Date.now().toString(36);
const co=need('co',await o.call('companies',{method:'POST',company:false,json:{name:'R152 Intake Inc '+stamp,province:'NS',country:'Canada',businessType:'corporation',currency:'CAD',accountingBasis:'accrual',moduleMode:'accounting',fiscalYearEnd:'12-31',booksStartDate:'2026-01-01',taxRegistered:true,taxNumber:'123456789RT0001',coaMode:'default'}}));
const CID=co.company.id;o.cid=CID;
const acct=code=>sql(`SELECT id FROM accounts WHERE company_id='${CID}' AND code='${code}'`);
const vend=async(name,email)=>need('vend',await o.call('vendors',{method:'POST',json:{name,email,province:'NS',country:'Canada',paymentTerms:30}})).vendor.id;
const NW=await vend('Northwind Office Supply Ltd.','billing@northwind-office.example'),FB=await vend('Fournitures Boréales Inc.','comptes@fournitures-boreales.example'),HF=await vend('Harbour Freight Logistics','ar@harbourfreight-log.example');
// History for coding suggestions: two earlier Northwind invoices. Paper and the chair went to 6400, toner to 6300,
// so 6400 is the vendor's most used account (2 invoices) and toner lines match 6300 by wording.
for(const [n,date,lines] of [['NW-2025-0901','2026-01-20',[{description:'Copy paper, letter, 5 reams',quantity:1,unitPriceCents:2750,accountId:acct('6400'),taxCodeId:''},{description:'Toner cartridge HP 26A',quantity:1,unitPriceCents:18950,accountId:acct('6300'),taxCodeId:''}]],['NW-2026-0015','2026-02-10',[{description:'Desk chair',quantity:1,unitPriceCents:21000,accountId:acct('6400'),taxCodeId:''}]]])
  need('hist',await o.call('bills',{method:'POST',json:{vendorId:NW,number:n,billDate:date,currency:'CAD',taxEntryMode:'exclusive',lines,issue:true}}));
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',args:['--no-proxy-server','--host-resolver-rules=MAP gate.test 127.0.0.1']});
const ctx=await b.newContext({viewport:{width:1440,height:900},ignoreHTTPSErrors:true});const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message.slice(0,160)));
// Every request body the intake screen sends is kept, to show that no extracted text leaves the browser.
const sent=[];p.on('request',r=>{if(/native-ap-ar\/document\/(memory|review)/.test(decodeURIComponent(r.url()))&&r.method()==='POST')sent.push({url:r.url(),body:r.postData()||''})});
await p.goto('https://gate.test/app.html');await p.fill('#sr-login-form input[name=email]','owner@gate.test');await p.fill('#sr-login-form input[name=password]','Gate!Owner#2026pw');await p.click('#sr-login-form button[type=submit]');
await p.waitForFunction(()=>window.TeghPortal&&document.querySelector('.sidebar,.topbar'),null,{timeout:40000});
await p.evaluate(id=>{localStorage.setItem('sr-accountax-company',id);localStorage.setItem('sr-accountax-companies',JSON.stringify([id]))},CID);await p.goto('https://gate.test/app.html');await p.waitForFunction(()=>window.TeghPortal&&document.querySelector('.sidebar,.topbar'),null,{timeout:40000});
const t=async(id,title,fn)=>{try{const r=await fn();rec(id,A,title,r.ok?'PASS':'FAIL',r.info||'')}catch(e){await p.screenshot({path:`/srv/gate/ev/shots/r152-fail-${id}.png`}).catch(()=>{});rec(id,A,title,'FAIL',e.message.replace(/\s+/g,' ').slice(0,600))}};
const c=v=>v==null?null:Math.round(v*100);

// ===================== Stage 1: statements =====================
const conv=(file,opts={})=>p.evaluate(async({b64,opts})=>{const bytes=Uint8Array.from(atob(b64),ch=>ch.charCodeAt(0));
  if(globalThis.TeghLoadFeature)await globalThis.TeghLoadFeature('ocr');const pd=await globalThis.TeghNativeOCR.extractStatementPages(new File([bytes],'s.pdf',{type:'application/pdf'}),{onPassword:()=>null,onProgress:()=>{}});
  const m=await import('/assets/tegh-bank-converter-v5990.js?v=5990-r152-tegh');const parsed=m.convertPages(pd.pages,{layout:'auto',dateOrder:'auto',accountType:'',...opts});
  return {rows:parsed.rows.map(r=>({date:r.date,desc:r.description,cents:Math.round(r.amount*100),manual:!!r.needsManualAmount})),opening:parsed.metadata?.openingBalance??null,closing:parsed.metadata?.closingBalance??null,
    balanced:parsed.layoutCheck?.balanced??null,isCard:parsed.layoutCheck?.isCard??null,text:m.balanceCheckText(parsed.layoutCheck),statements:parsed.statements||null,section:parsed.section||null,account:parsed.accountLastFour||null}},{b64:fs.readFileSync(file).toString('base64'),opts});
const titles={G:'RBC-style (DD Mon, "Cheques & Debits", two pages)',H:'BMO-style (headings on two lines, "Closing totals")',I:'Scotia-style (MM/DD, "Balance forward", overdrawn balances)',J:'Desjardins-style French (code column, "02 janv.", French amounts)',
  K:'National Bank-style French (DD/MM numeric dates, "Solde précédent")',L:'Tangerine-style (signed amounts, full dates)',M:'Amex-style card (Dec→Jan, negative credits)',N:'French Visa (two date columns, "CR" credits)',
  P:'card with MM/DD dates across December→January',Q:'credit union (DR/CR column, OD balances)',R:'two-line rows (amount on the line under the description)',S:'French with thousands split into separate text pieces'};
for(const k of Object.keys(titles)){const e=XS[k];await t(`ST-${k}`,`Statement ${k} — ${titles[k]}: every row, the net, opening and closing balances, first/last dates; balances agree`,async()=>{const r=await conv(`${FX}/${k}.pdf`);
  const net=r.rows.reduce((s,x)=>s+(x.manual?0:x.cents),0),got=[r.rows.length,net,c(r.opening),c(r.closing),r.rows[0]?.date,r.rows.at(-1)?.date,r.balanced,!!r.isCard,e.sample.every(s=>r.rows.some(x=>x.date===s.date&&x.cents===s.cents))],want=[e.rows,e.net,e.opening,e.closing,e.first,e.last,true,e.card,true];
  return {ok:JSON.stringify(got)===JSON.stringify(want),info:`got ${JSON.stringify(got)} want ${JSON.stringify(want)}`}})}
await t('ST-O1','A PDF with three statements (Jan and Feb for …4567, Jan for …9012): all three are listed; for account …4567 both months are read together and each starts at the previous closing balance',async()=>{const r=await conv(`${FX}/O.pdf`,{accountLastFour:'4567'}),[s1,s2]=XS.O.statements;
  const got=[r.statements?.map(s=>s.account),r.section,r.rows.length,c(r.opening),c(r.closing),r.balanced,/Each statement starts at the closing balance of the one before it ✓/.test(r.text),r.account],want=[['4567','4567','9012'],'acct:4567',s1.rows+s2.rows,s1.opening,s2.closing,true,true,'4567'];
  return {ok:JSON.stringify(got)===JSON.stringify(want)&&XS.O.chain===true,info:`got ${JSON.stringify(got)} | ${r.text.slice(0,140)}`}});
await t('ST-O2','The third statement in that PDF can be chosen on its own: 2 rows for account …9012 with its own balances',async()=>{const r=await conv(`${FX}/O.pdf`,{section:'2'}),e=XS.O.statements[2];
  const got=[r.rows.length,r.rows.reduce((s,x)=>s+x.cents,0),c(r.opening),c(r.closing),r.balanced,r.account];return {ok:JSON.stringify(got)===JSON.stringify([e.rows,e.net,e.opening,e.closing,true,'9012']),info:JSON.stringify(got)}});
await t('ST-AMB','Numeric dates that read correctly both ways inside the statement period (01/02 and 02/01 in Jan–Feb) are not guessed; choosing day/month reads them',async()=>{const r=await p.evaluate(async()=>{const L=await import('/assets/tegh-statement-layout-r152.js?v=5990-r152-tegh');
  const cell=(text,x,w)=>({text,x,width:w});const line=(y,cells)=>({page:1,y,cells});
  const lines=[line(720,[cell('Statement period Jan 1, 2026 to Feb 28, 2026',40,200)]),line(700,[cell('Date',40,20),cell('Description',90,50),cell('Withdrawals',300,50),cell('Deposits',380,40),cell('Balance',460,40)]),line(690,[cell('01/01',40,20),cell('Opening balance',90,60),cell('1,000.00',470,30)]),
    line(680,[cell('01/02',40,20),cell('Coffee',90,30),cell('5.00',335,15)]),line(670,[cell('02/01',40,20),cell('Refund',90,30),cell('10.00',405,20),cell('1,005.00',470,30)])];
  const auto=L.parseStatementLayout(lines,{}),dmy=L.parseStatementLayout(lines,{dateOrder:'dmy'});return {amb:!!auto.dateOrderAmbiguous,undated:auto.undated,dates:dmy?.rows.map(x=>x.date),reconciled:dmy?.reconciled}});
  return {ok:r.amb&&r.undated===2&&JSON.stringify(r.dates)===JSON.stringify(['2026-02-01','2026-01-02']),info:JSON.stringify(r)}});
await t('ST-REG','The R145 statements (bank, card, page totals, missing line, ISO dates, no headings) read exactly as before',async()=>{const out=[];for(const [k,ty] of [['A',''],['B','credit_card'],['C',''],['D',''],['E',''],['F','']]){const r=await conv(`/srv/gate/t/conv/fx/${k}.pdf`,{accountType:ty});out.push([k,r.rows.length,X145[k].rows,r.balanced,X145[k].balanced??null,r.statements?.length??1])}
  return {ok:out.every(([k,n,en,bal,eb,ns])=>n===en&&(eb==null||(k==='F'?bal===null:bal===eb))&&ns===1),info:JSON.stringify(out)}});
const d0close=async()=>{const x=p.locator('.tegh-converter-panel [data-converter-cancel]').first();if(await x.count())await x.click();await p.waitForTimeout(500)};
await t('ST-UI','Converter screen: a PDF with three statements says so, lists them under "Statement in this PDF", and reading statement 3 shows its 2 rows',async()=>{const bank=sql(`SELECT id FROM bank_accounts WHERE company_id='${CID}' AND account_type='bank' LIMIT 1`);
  await p.evaluate(()=>TeghPortal.invokeMenuAction('Banking','Upload Statement'));const f=p.locator('[data-converter-form]').last();await f.waitFor({timeout:20000});await f.locator('select[name=bankAccountId]').selectOption(bank);await f.locator('input[type=file]').setInputFiles(`${FX}/O.pdf`);await f.locator('button[type=submit]').click();
  const d=p.locator('.tegh-converter-panel');await d.locator('[data-converter-row]').first().waitFor({timeout:30000});const st=await d.locator('[data-converter-status]').textContent();const opts=await d.locator('select[name=section] option').allTextContents();
  await d.locator('select[name=section]').selectOption('2');await d.locator('form[data-converter-options] button[type=submit]').click();await p.waitForTimeout(800);const n=await d.locator('[data-converter-row]').count();await p.screenshot({path:'/srv/gate/ev/shots/r152-statements-picker.png'});await d0close();
  return {ok:/holds 3 statements/.test(st)&&opts.length>=3&&opts.some(x=>/…9012/.test(x))&&n===2,info:`${st.slice(0,90)} | options ${opts.length}: ${opts.slice(0,4).join(' / ').slice(0,200)} | rows after choosing 3: ${n}`}});

// ===================== Stage 2: invoices =====================
const intake=async()=>{const left=await p.locator('.tegh-converter-scrim').count();if(left)console.log('converter dialog still open:',left);await p.evaluate(()=>document.querySelectorAll('.tegh-converter-scrim').forEach(x=>x.remove()));await p.evaluate(()=>TeghPortal.invokeMenuAction('Payables','Document Intake'));await p.locator('[data-native-document-upload]').waitFor({timeout:20000})};
const upload=async f=>{await p.waitForLoadState('networkidle').catch(()=>{});const form=p.locator('[data-native-document-upload]');if(!await form.locator('button[type=submit]').isVisible()){await p.locator('summary:visible',{hasText:/^Upload document/}).first().click();await form.locator('button[type=submit]').waitFor({state:'visible',timeout:10000})}await form.locator('select[name=documentType]').selectOption('vendor_bill',{force:true});await form.locator('input[name=file]').setInputFiles(f);
  // The intake list refreshes after the previous save and can close the Upload menu; reopen it (the chosen file stays) before submitting.
  await p.waitForTimeout(300);if(!await form.locator('button[type=submit]').isVisible()){await p.locator('summary:visible',{hasText:/^Upload document/}).first().click();await form.locator('button[type=submit]').waitFor({state:'visible',timeout:10000})}
  await form.locator('button[type=submit]').click()};
const docByName=name=>sql(`SELECT id FROM native_agent_documents WHERE company_id='${CID}' AND original_name='${name}' ORDER BY created_at DESC LIMIT 1`);
const waitDoc=async name=>{for(let i=0;i<120;i++){const id=docByName(name);if(id&&sql(`SELECT extraction_method FROM native_agent_documents WHERE id='${id}'`)!=='none')return id;await p.waitForTimeout(500)}throw Error('no document '+name)};
const candidate=id=>JSON.parse(sql(`SELECT candidate_json FROM native_agent_documents WHERE id='${id}'`));
const card=async id=>{const loc=p.locator(`[data-native-document="${id}"]`);await p.waitForTimeout(300);if(!await loc.first().isVisible().catch(()=>false)){const k=p.locator('[data-r22-review-key]').filter({hasText:sql(`SELECT original_name FROM native_agent_documents WHERE id='${id}'`)}).first();if(await k.count())await k.click()}await loc.first().waitFor({timeout:30000});return loc.first()};
const doc=async id=>(need('docs',await o.call('native-ap-ar/documents')).documents||[]).find(d=>d.id===id);
// Verify through the API with the reviewed candidate (the screen path is exercised in IN-02).
const verify=async(id,patch)=>{const d=await doc(id);return o.call('native-ap-ar/document/review',{method:'POST',json:{documentId:id,extractionMethod:'pdf_text',candidate:{...d.candidate,...patch},verified:true}})};
const fsTmp='/srv/gate/t/conv/ix152-upload';fs.mkdirSync(fsTmp,{recursive:true});const named=(k,name)=>{fs.copyFileSync(`${IX}/${k}.pdf`,`${fsTmp}/${name}`);return `${fsTmp}/${name}`};

let V1;
await t('IN-01','Vendor invoice (EN): the 4 lines are read as a table — description (wrapped line joined, item codes left out), quantity, unit price, amount, each checked — and they add up to the subtotal',async()=>{await intake();await upload(named('V1','northwind-0142.pdf'));V1=await waitDoc('northwind-0142.pdf');const cd=candidate(V1),e=XI.V1;
  const got=cd.lineItems.map(l=>[l.description,l.quantity,l.unitCents,l.amountCents,l.checked]),want=e.lines.map(l=>[l.description,l.quantity,l.unitCents,l.amountCents,true]);
  const cardEl=await card(V1);const chk=await cardEl.locator('[data-line-check]').textContent();const rows=await cardEl.locator('[data-intake-line]').count();await p.screenshot({path:'/srv/gate/ev/shots/r152-intake-lines.png'});
  return {ok:JSON.stringify(got)===JSON.stringify(want)&&cd.lineCheck==='subtotal'&&rows===4&&/add up to the subtotal ✓/.test(chk),info:`${JSON.stringify(got).slice(0,260)} | ${chk}`}});
await t('IN-02','Verifying it on the screen (vendor preselected by name) stores the reader\'s own candidate for learning — not the document text — and starts the supplier memory',async()=>{const el=await card(V1);await el.locator('select[name=partyId]').selectOption(NW);await el.locator('input[name=verified]').check();await el.locator('button[type=submit]',{hasText:'Save Human Review'}).click();
  for(let i=0;i<40&&sql(`SELECT state FROM native_agent_documents WHERE id='${V1}'`)!=='ready';i++)await p.waitForTimeout(250);
  const extracted=sql(`SELECT extracted_json FROM native_agent_documents WHERE id='${V1}'`),mem=sql(`SELECT CONCAT_WS('|',number_shape,confirmations) FROM vendor_document_memory WHERE company_id='${CID}' AND vendor_id='${NW}'`);
  return {ok:sql(`SELECT state FROM native_agent_documents WHERE id='${V1}'`)==='ready'&&extracted.includes('NW-2026-0142')&&!/Bill to|Gate Test Company|Factur/.test(extracted)&&mem==='AA-9999-9999|1',info:`state ready; extracted candidate ${extracted.length} chars, no document text; memory ${mem}`}});
await t('IN-03','Coding suggestions come from this vendor\'s earlier invoices: paper → 6400 and toner → 6300 by wording; the organizer and delivery get the vendor\'s most used account 6400',async()=>{const r=need('coding',await o.call(`native-ap-ar/document/coding&documentId=${V1}`));
  const got=[r.invoicesSeen,r.default?.accountId===acct('6400'),r.lines.map(l=>[l.index,l.accountId===acct('6400')?'6400':l.accountId===acct('6300')?'6300':l.accountId,l.source])];
  return {ok:JSON.stringify(got)===JSON.stringify([2,true,[[0,'6400','line_match'],[1,'6300','line_match'],[2,'6400','vendor_default'],[3,'6400','vendor_default']]]),info:JSON.stringify(got)+' | '+r.default?.reason}});
let BILL;
await t('IN-04','"Open in Vendor Invoice Form" fills the vendor invoice form with the 4 lines and their suggested accounts, compares its total with the document total (a wrong tax code shows up); saving the draft links the document to the new vendor invoice',async()=>{await intake();const el=await card(V1);await el.locator('[data-document-prepare]').click();
  await p.locator('[data-r151-form]').waitFor({timeout:20000});const note=await p.locator('[data-r151-intake]').textContent();const rows=p.locator('tr[data-r151-line]');await p.waitForTimeout(400);
  const lines=[];for(let i=0;i<await rows.count();i++){const r=rows.nth(i);const d=await r.locator('[name=description]').inputValue();if(!d)continue;lines.push([d,await r.locator('[name=qty]').inputValue(),await r.locator('[name=rate]').inputValue(),await r.locator('[name=accountId]').inputValue()])}
  // The vendor's province code (NS HST 14%) is preselected, but the invoice charged GST 5%: the form must say its total differs from the document's.
  const warn=p.locator('[data-r151-intake-check]');const before=[await warn.getAttribute('data-state'),await warn.textContent()];
  const gst=sql(`SELECT id FROM tax_codes WHERE company_id='${CID}' AND code='GST'`);for(let i=0;i<await rows.count();i++){const sel=rows.nth(i).locator('[name=taxKey]');if(await rows.nth(i).locator('[name=description]').inputValue())await sel.selectOption(gst)}
  await p.waitForTimeout(300);const after=[await warn.getAttribute('data-state'),await warn.textContent()];
  await p.screenshot({path:'/srv/gate/ev/shots/r152-intake-to-form.png'});await p.locator('[data-r151-save=draft]').click();
  for(let i=0;i<40&&!BILL;i++){await p.waitForTimeout(400);BILL=sql(`SELECT linked_entity_id FROM native_agent_documents WHERE id='${V1}' AND state='linked'`)}
  const saved=BILL?sql(`SELECT CONCAT_WS('|',b.number,b.status,b.subtotal_cents,b.total_cents,(SELECT GROUP_CONCAT(CONCAT(bl.foreign_amount_cents,'@',a.code) ORDER BY bl.sort_order) FROM bill_lines bl JOIN accounts a ON a.id=bl.account_id WHERE bl.bill_id=b.id)) FROM bills b WHERE b.id='${BILL}'`):'';
  const e=XI.V1,want=`NW-2026-0142|draft|${e.subtotal}|${e.total}|16497@6400,37900@6300,2345@6400,1500@6400`;
  return {ok:/Prefilled from Document Intake/.test(note)&&lines.length===4&&lines[1][0]===e.lines[1].description&&lines[1][1]==='2'&&lines[1][2]==='189.50'&&lines[1][3]===acct('6300')&&before[0]==='warn'&&/\$611\.54/.test(before[1])&&/check the tax code/.test(before[1])&&after[0]==='ok'&&/Matches the document total of \$611\.54 ✓/.test(after[1])&&saved===want,info:`form lines ${lines.length}; check before: ${before[1]} | after GST: ${after[1]} | saved ${saved||'(not linked)'}`}});
let V6;
await t('IN-05','The same invoice sent again (a different file) is flagged as a duplicate of the saved vendor invoice, by supplier and number',async()=>{await intake();await upload(named('V6','northwind-0142-reminder.pdf'));V6=await waitDoc('northwind-0142-reminder.pdf');
  const r=await verify(V6,{partyId:NW});const d=await doc(V6);await intake();const el=await card(V6);const txt=await el.locator('[data-document-duplicates]').textContent();await p.screenshot({path:'/srv/gate/ev/shots/r152-intake-duplicate.png'});
  return {ok:r.s===200&&d.duplicates?.some(x=>x.kind==='bill'&&x.id===BILL&&x.reason==='number')&&/same supplier and number/.test(txt)&&/NW-2026-0142/.test(txt),info:txt.replace(/\s+/g,' ').slice(0,200)}});
await t('IN-06','The suggested account is preselected on its draft form, and a draft or workflow from the duplicate is refused until "this is a different invoice" is confirmed',async()=>{const el=await card(V6);const sel=await el.locator('[data-document-import-draft] select[name=categoryAccountId]').inputValue(),why=await el.locator('[data-coding-reason]').textContent();
  const d=await doc(V6);const no=await o.call('native-ap-ar/document/prepare',{method:'POST',json:{documentId:V6,sourceRevisionHash:d.sourceRevisionHash}});const yes=await o.call('native-ap-ar/document/prepare',{method:'POST',json:{documentId:V6,sourceRevisionHash:d.sourceRevisionHash,confirmNotDuplicate:true}});
  return {ok:sel===acct('6400')&&/earlier invoices from this vendor/.test(why)&&no.s===409&&no.b?.code==='native_document_possible_duplicate'&&yes.s===200,info:`preselected ${sel===acct('6400')?'6400':sel}; "${why}"; without confirmation ${no.s} ${no.b?.code}; with ${yes.s}`}});
let V2,V3;
await t('IN-07','French invoice with 03/04/2026: the date is not guessed (two readings offered); its lines (Qté, Prix unitaire, Montant) are read and checked',async()=>{await intake();await upload(named('V2','boreales-88231.pdf'));V2=await waitDoc('boreales-88231.pdf');const cd=candidate(V2),e=XI.V2;
  return {ok:cd.documentDate===undefined&&cd.alternatives.some(a=>a.documentDate===e.date&&a.dateOrder==='dmy')&&cd.lineItems.length===3&&cd.lineItems.every(l=>l.checked)&&cd.lineCheck==='subtotal'&&cd.totalCents===e.total,info:JSON.stringify({alts:cd.alternatives,lines:cd.lineItems.map(l=>l.amountCents),total:cd.totalCents})}});
await t('IN-08','Choosing "April 3, 2026" and verifying teaches the supplier memory day/month order for this supplier',async()=>{await intake();const el=await card(V2);await el.locator('[data-date-choice]',{hasText:'April 3, 2026'}).click();await el.locator('select[name=partyId]').selectOption(FB);await el.locator('input[name=verified]').check();await el.locator('button[type=submit]',{hasText:'Save Human Review'}).click();
  let m='';for(let i=0;i<40&&!m;i++){await p.waitForTimeout(250);m=sql(`SELECT date_order FROM vendor_document_memory WHERE company_id='${CID}' AND vendor_id='${FB}'`)}return {ok:m==='dmy',info:'memory date order '+m}});
await t('IN-09','The next invoice from that supplier (05/06/2026) is read as June 5, 2026 from supplier memory, and the screen says why',async()=>{await intake();await upload(named('V3','boreales-88457.pdf'));V3=await waitDoc('boreales-88457.pdf');const cd=candidate(V3);const el=await card(V3);const note=await el.locator('[data-supplier-memory]').textContent();await p.screenshot({path:'/srv/gate/ev/shots/r152-intake-memory.png'});
  return {ok:cd.documentDate===XI.V3.date&&/day\/month/.test(cd.learned?.join(' ')||'')&&/Supplier memory applied/i.test(note),info:`${cd.documentDate} | ${note.replace(/\s+/g,' ').slice(0,140)}`}});
let V4,V5;
await t('IN-10','A supplier whose invoice number sits under an unusual label ("Our reference"): once the number is corrected by hand, the next invoice\'s number is found by the learned pattern',async()=>{await intake();await upload(named('V4','harbour-2031.pdf'));V4=await waitDoc('harbour-2031.pdf');const first=candidate(V4).documentNumber||'';
  const r=await verify(V4,{partyId:HF,documentNumber:'HF/77-2031'});const shape=sql(`SELECT number_shape FROM vendor_document_memory WHERE company_id='${CID}' AND vendor_id='${HF}'`);
  await intake();await upload(named('V5','harbour-2096.pdf'));V5=await waitDoc('harbour-2096.pdf');const cd=candidate(V5);
  return {ok:first!=='HF/77-2031'&&r.s===200&&shape==='AA/99-9999'&&cd.documentNumber==='HF/77-2096'&&/number pattern/.test(cd.learned?.join(' ')||''),info:`first read "${first}", learned ${shape}, next read "${cd.documentNumber}"`}});
await t('IN-11','Privacy: the memory lookup sends only the extracted identity (name, email, business number, address) and no request carries the document text',async()=>{const keys=new Set();let text=false;for(const s of sent){let j={};try{j=JSON.parse(s.body)}catch{};if(/memory/.test(decodeURIComponent(s.url)))Object.keys(j).forEach(k=>keys.add(k));if(/rawText|Bill to:|Facturé à/.test(s.body))text=true}
  const extra=[...keys].filter(k=>!['partyName','partyEmail','businessIdentifier','address'].includes(k));return {ok:sent.some(s=>/memory/.test(decodeURIComponent(s.url)))&&!extra.length&&!text,info:`${sent.length} requests; memory keys ${[...keys].join(',')}; document text sent: ${text}`}});
await t('IN-12','Company isolation: another company cannot read this company\'s coding suggestions or supplier memory',async()=>{const other=need('co2',await o.call('companies',{method:'POST',company:false,json:{name:'R152 Other '+stamp,province:'ON',country:'Canada',businessType:'corporation',currency:'CAD',accountingBasis:'accrual',moduleMode:'accounting',fiscalYearEnd:'12-31',booksStartDate:'2026-01-01',taxRegistered:false,coaMode:'default'}})).company.id;
  const coding=await o.call(`native-ap-ar/document/coding&documentId=${V1}`,{headers:{'X-Company-Id':other},company:false});const mem=await o.call('native-ap-ar/document/memory',{method:'POST',json:{partyName:'Northwind Office Supply Ltd.'},headers:{'X-Company-Id':other},company:false});
  return {ok:!!V1&&!!sql(`SELECT 1 FROM vendor_document_memory WHERE company_id='${CID}' LIMIT 1`)&&coding.s===404&&mem.s===200&&mem.b.memory===null&&mem.b.vendorId===null,info:`coding ${coding.s}; memory ${mem.s} ${JSON.stringify(mem.b?.memory)}`}});
await t('IN-13','Backup export includes the supplier memory',async()=>{const r=await o.call('backup/export',{method:'POST',json:{},raw:true});const buf=Buffer.from(await r.arrayBuffer());fs.writeFileSync('/tmp/r152-backup.zip',buf);
  let body='';try{body=execFileSync('unzip',['-p','/tmp/r152-backup.zip'],{encoding:'utf8',maxBuffer:200e6})}catch(e){body=String(e.stdout||'')}fs.unlinkSync('/tmp/r152-backup.zip');
  return {ok:r.status===200&&/vendorDocumentMemory/.test(body)&&body.includes('AA/99-9999'),info:`${r.status}, ${buf.length} bytes zipped, supplier memory present: ${/vendorDocumentMemory/.test(body)}`}});
rec('IN-JS',A,'No page errors during the R152 journeys',errs.length?'FAIL':'PASS',errs.slice(0,3).join(' | '));
await b.close();save('r152.json');
