// Guided mode, end to end: a fresh Ontario company with eight imported September statement lines is booked the
// way a Guided user would: Home → Match and Post, single and bulk posting with GST/HST, exclude and restore, void
// and re-post, posting at phone width, matching, month-end checklist and the owner reports. Every journal is
// compared with amounts worked out by hand (13% HST included in the bank amount), never with the app's own maths.
import {chromium} from '/opt/node22/lib/node_modules/playwright/index.mjs';import {rec,save,sql,S} from './lib.mjs';import {execFileSync} from 'child_process';import fs from 'fs';
const A='GUIDED';
execFileSync('mysql',['tegh_gate','-e','DELETE FROM login_attempts']);
const setup=JSON.parse(execFileSync('node',['/srv/gate/t/guided/setup.mjs'],{encoding:'utf8',cwd:'/srv/gate/t/guided'}).trim().split('\n').pop());
const CID=setup.CID;rec('G-00',A,`Guided test company created with ${setup.imported} imported statement lines`,setup.imported===8&&[200,201].includes(setup.approve)?'PASS':'FAIL',JSON.stringify({imported:setup.imported,approve:setup.approve}));
// Hand-worked postings in cents: [account code, debit, credit]. HST-included: net = gross/1.13, tax = gross − net.
const EXPECT={
  'STAPLES OFFICE SUPPLIES 4411':[['6400',10000,0],['1100',1300,0],['1000',0,11300]],
  'CLIENT DEPOSIT HARBOUR DESIGN':[['1000',56500,0],['4000',0,50000],['2100',0,6500]],
  'MONTHLY ACCOUNT FEE':[['6800',2500,0],['1000',0,2500]],
  'ROGERS WIRELESS 9001':[['6300',5000,0],['1100',650,0],['1000',0,5650]],
  'ROGERS WIRELESS 9002':[['6300',5000,0],['1100',650,0],['1000',0,5650]],
  'ROGERS WIRELESS 9003':[['6300',5000,0],['1100',650,0],['1000',0,5650]],
  'OWNER PERSONAL PURCHASE':[['3100',4000,0],['1000',0,4000]],
  'ADOBE SOFTWARE SUBSCRIPTION':[['6200',3000,0],['1100',390,0],['1000',0,3390]],
};
const FINAL={'1000':18360,'1100':3640,'2100':-6500,'3100':4000,'4000':-50000,'6200':3000,'6300':15000,'6400':10000,'6800':2500};
const norm=l=>l.map(x=>x.join(':')).sort().join(' ');
const journal=desc=>{const r=sql(`SELECT a.code,l.debit_cents,l.credit_cents FROM bank_transactions b JOIN journal_entries j ON j.id=b.journal_entry_id AND j.voided_at IS NULL JOIN journal_lines l ON l.journal_entry_id=j.id JOIN accounts a ON a.id=l.account_id WHERE b.company_id='${CID}' AND b.description='${desc}'`);return r?r.split('\n').map(x=>{const [c,d,k]=x.split('\t');return [c,Number(d),Number(k)]}):[]};
const status=desc=>sql(`SELECT status FROM bank_transactions WHERE company_id='${CID}' AND description='${desc}'`);
const money=c=>(c/100).toLocaleString('en-CA',{minimumFractionDigits:2,maximumFractionDigits:2});

const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',args:['--no-proxy-server','--host-resolver-rules=MAP gate.test 127.0.0.1']});
const ctx=await b.newContext({viewport:{width:1440,height:900},ignoreHTTPSErrors:true});const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message.slice(0,200)));p.on('dialog',d=>d.accept());
await p.goto('https://gate.test/app.html');await p.fill('#sr-login-form input[name=email]','owner@gate.test');await p.fill('#sr-login-form input[name=password]','Gate!Owner#2026pw');await p.click('#sr-login-form button[type=submit]');
const ready=()=>p.waitForFunction(()=>window.TeghPortal&&document.querySelector('.sidebar,.topbar'),null,{timeout:60000});await ready();
await p.evaluate(id=>{localStorage.setItem('sr-accountax-company',id);localStorage.setItem('sr-accountax-companies',JSON.stringify([id]))},CID);await p.goto('https://gate.test/app.html');await ready();
await p.evaluate(()=>TeghPortal.switchBookkeepingMode('owner'));
const t=async(id,title,fn)=>{try{const r=await fn();rec(id,A,title,r.ok?'PASS':'FAIL',r.info)}catch(e){await p.screenshot({path:`/srv/gate/t/guided/fail-${id}.png`}).catch(()=>{});const dlg=await p.evaluate(()=>[...document.querySelectorAll('.srp-modal-scrim')].map(x=>x.innerText.slice(0,160)).join(' | ')).catch(()=>'');rec(id,A,title,'FAIL','error: '+e.message.replace(/\x1b\[[0-9;]*m/g,'').split('\n').filter(l=>/Timeout|intercepts|waiting for|not visible|outside/.test(l)).slice(0,4).join(' / ').slice(0,400)+(dlg?' · dialog: '+dlg:''))}};
const visText=()=>p.evaluate(()=>[...document.querySelectorAll('[data-srp-page]')].filter(x=>x.offsetParent).map(x=>x.innerText).join('\n'));
const home=async()=>{await p.locator('.sidebar nav button:has-text("Home")').first().click();await p.waitForSelector('[data-srp-page="guided-bookkeeping"] .tegh-guided-home-head',{timeout:30000});await p.waitForTimeout(800)};
const matchPost=async()=>{const bank=p.locator('.sidebar nav button:has-text("Banking")').first(),sub=p.locator('.sidebar nav button[data-srp-menu="Banking"]:has-text("Match and Post")').first();await p.waitForTimeout(400);if(await bank.getAttribute('aria-expanded')!=='true'){await bank.click();await p.waitForFunction(()=>[...document.querySelectorAll('.sidebar nav button')].find(x=>/^Banking/.test(x.textContent.trim()))?.getAttribute('aria-expanded')==='true',null,{timeout:10000})}await sub.waitFor({state:'visible'});await p.waitForTimeout(300);await sub.click();await waitList()};
const waitList=async()=>{await p.waitForSelector('[data-srp-page="bank-reconciliation"] [data-r28-bank-row]',{timeout:30000});await p.waitForTimeout(600)};
const rowsState=()=>p.evaluate(()=>Object.fromEntries([...document.querySelectorAll('[data-r28-bank-row]')].map(r=>[r.querySelector('.r27-recon-description span')?.textContent.trim(),r.querySelector('.srp-status')?.textContent.trim()])));
const okDialog=async()=>{await p.waitForSelector('.tegh-action-dialog button[type=submit]',{timeout:15000});const msg=(await p.locator('.tegh-action-dialog').innerText()).replace(/\s+/g,' ');await p.click('.tegh-action-dialog button[type=submit]');return msg};
const rowAction=async(text,sel)=>{const row=p.locator(`[data-bank-list-row]:has-text("${text}")`).first(),sum=row.locator('details.r22-row-actions > summary');let ticked=false;if(await sum.count()){await sum.click();await p.waitForTimeout(200);ticked=await row.locator('input[data-bank-list-select]').isChecked()}const floating=p.locator(`#tegh-overlay-root ${sel}`);await ((await floating.count())?floating.first():row.locator(sel)).click();return ticked};
const pick=async descs=>{for(const d of descs)await p.locator(`[data-r28-bank-row]:has-text("${d}") input[data-r28-bank-select]`).check();await p.waitForSelector('[data-r28-post-form]')};
const fill=async(code,tax)=>{const v=await p.evaluate(code=>[...document.querySelectorAll('[data-r28-post-form] select[name=accountId] option')].find(o=>o.textContent.startsWith(code+' ·'))?.value,code);if(!v)throw Error('no account option '+code);
  await p.selectOption('[data-r28-post-form] select[name=accountId]',v);const tv=tax==='NO_TAX'?'NO_TAX':await p.evaluate(()=>[...document.querySelectorAll('[data-r28-post-form] select[name=taxCode] option')].find(o=>/Ontario/.test(o.textContent))?.value);if(!tv)throw Error('no Ontario HST tax option');await p.selectOption('[data-r28-post-form] select[name=taxCode]',tv);await p.waitForTimeout(300);
  return p.evaluate(()=>[...document.querySelectorAll('[data-r28-post-preview] tbody tr,[data-r28-post-preview] tfoot tr')].map(r=>[...r.cells].map(c=>c.textContent.trim()).join(' | ')))};
const submit=async descs=>{await p.click('[data-r28-post]');await okDialog();await p.waitForFunction(ds=>{const m=Object.fromEntries([...document.querySelectorAll('[data-r28-bank-row]')].map(r=>[r.querySelector('.r27-recon-description span')?.textContent.trim(),r.querySelector('.srp-status')?.textContent.trim()]));return ds.every(d=>m[d]==='Posted')},descs,{timeout:30000})};
const prevHas=(prev,cents)=>cents.every(c=>prev.some(l=>l.includes(money(c))));
const postOne=async(id,desc,code,tax,label)=>t(id,`Guided Match and Post: "${desc}" posts to ${label}; the preview and the journal show ${EXPECT[desc].map(([c,d,k])=>`${c} ${d?'Dr '+money(d):'Cr '+money(k)}`).join(', ')}`,async()=>{
  errs.length=0;await pick([desc]);const prev=await fill(code,tax);await submit([desc]);const j=journal(desc),ok=norm(j)===norm(EXPECT[desc]);
  return {ok:ok&&prevHas(prev,EXPECT[desc].map(([,d,k])=>d||k))&&!errs.length,info:`preview: ${prev.join(' / ')}; journal: ${norm(j)}; want ${norm(EXPECT[desc])}; errors ${errs.join(';')||'none'}`}});

await p.waitForSelector('[data-srp-page="guided-bookkeeping"] .tegh-guided-home-head',{timeout:30000}).catch(()=>{});
await t('G-01','Guided Home after the import: mode is Guided, the to-do card says "8 Transactions To Post" and the Banking menu badge shows 8',async()=>{await home();const mode=await p.evaluate(()=>document.documentElement.dataset.bookkeepingMode);const txt=await visText();
  const badge=await p.evaluate(()=>[...document.querySelectorAll('.sidebar nav button')].find(x=>/Banking/.test(x.textContent))?.querySelector('em')?.textContent.trim());
  return {ok:mode==='guided'&&/8 Transactions To Post/i.test(txt)&&badge==='8',info:`mode ${mode}; card ${/8 Transactions To Post/i.test(txt)}; badge ${badge}`}});
await t('G-02','The Home to-do button opens Match and Post with all 8 lines unposted and the statement balance $183.60 (565.00 − 113.00 − 25.00 − 3×56.50 − 40.00 − 33.90)',async()=>{await p.locator('[data-guided-task-action="review"]').click();await waitList();
  const s=await rowsState();const bal=await p.waitForFunction(()=>document.querySelector('[data-r127-balance] b')?.textContent,null,{timeout:15000}).then(h=>h.jsonValue());
  return {ok:Object.keys(s).length===8&&Object.values(s).every(v=>v==='Unposted')&&bal.includes('183.60'),info:`${Object.keys(s).length} rows; ${[...new Set(Object.values(s))].join(',')}; balance ${bal}`}});
await postOne('G-03','STAPLES OFFICE SUPPLIES 4411','6400','ON','6400 Office Supplies with GST/HST included');
await postOne('G-04','CLIENT DEPOSIT HARBOUR DESIGN','4000','ON','4000 Service Revenue with GST/HST included');
await postOne('G-05','MONTHLY ACCOUNT FEE','6800','NO_TAX','6800 Bank Charges with no tax');
const R=['ROGERS WIRELESS 9001','ROGERS WIRELESS 9002','ROGERS WIRELESS 9003'];
await t('G-06','Bulk: the three Rogers lines selected together post to 6300 Telephone with GST/HST as three journals of Dr 6300 50.00 / Dr 1100 6.50 / Cr 1000 56.50; the preview totals 150.00, 19.50 and 169.50',async()=>{errs.length=0;await pick(R);
  const head=await p.locator('[data-r28-right-panel] header h3').textContent();const prev=await fill('6300','ON');const btn=(await p.locator('[data-r28-post]').textContent()).trim();await submit(R);
  const js=R.map(journal),ok=js.every((j,i)=>norm(j)===norm(EXPECT[R[i]]));return {ok:ok&&/3 transactions selected/i.test(head)&&btn==='Post 3 Transactions'&&prevHas(prev,[15000,1950,16950])&&!errs.length,info:`panel "${head}"; button "${btn}"; preview ${prev.join(' / ')}; journals ${js.map(norm).join(' || ')}`}});
await t('G-07','After five lines are posted, Home counts 2 left to post, the Banking badge shows 2, and the Banking menu still opens after its badge changed',async()=>{await home();const txt=await visText();const badge=await p.evaluate(()=>[...document.querySelectorAll('.sidebar nav button')].find(x=>/Banking/.test(x.textContent))?.querySelector('em')?.textContent.trim());
  const bank=p.locator('.sidebar nav button:has-text("Banking")').first();await bank.click();const opened=await p.waitForFunction(()=>[...document.querySelectorAll('.sidebar nav button')].find(x=>/^Banking/.test(x.textContent.trim()))?.getAttribute('aria-expanded')==='true'&&document.querySelector('[data-srp-page="module-banking"]')?.offsetParent,null,{timeout:10000}).then(()=>true).catch(()=>false);
  return {ok:/2 Transactions To Post/i.test(txt)&&badge==='2'&&opened,info:`card ${(txt.match(/\d+ Transactions? To Post/i)||['none'])[0]}; badge ${badge}; after the badge changed, clicking Banking ${opened?'opens the Banking menu and page':'does nothing'}`}});
await t('G-08','Exclude: "Owner Personal Purchase" is excluded from the books from Match and Post; it leaves the list of lines to post, creates no journal, and Home counts 1',async()=>{await matchPost();await pick(['OWNER PERSONAL PURCHASE']);await p.click('[data-r121-exclude]');await okDialog();
  await p.waitForFunction(()=>{const r=[...document.querySelectorAll('[data-r28-bank-row]')].find(x=>/OWNER PERSONAL/.test(x.textContent));return !r||!/Unposted/.test(r.textContent)},null,{timeout:20000});
  const st=status('OWNER PERSONAL PURCHASE'),j=journal('OWNER PERSONAL PURCHASE');await home();const txt=await visText();return {ok:st==='excluded'&&!j.length&&/1 Transaction To Post/i.test(txt),info:`status ${st}; journal lines ${j.length}; home ${(txt.match(/\d+ Transactions? To Post/i)||['none'])[0]}`}});
await t('G-09','Restore: "Review excluded lines" lists the excluded line, its Actions menu opens without ticking the row, and Restore returns it; Match and Post shows it unposted again and Home counts 2',async()=>{await matchPost();await p.click('[data-r121-excluded]');await p.waitForSelector('[data-bank-list-row]',{timeout:20000});
  const listed=await p.locator('[data-bank-list-row]:has-text("OWNER PERSONAL PURCHASE")').count();const ticked=await rowAction('OWNER PERSONAL PURCHASE','[data-restore-line]');await p.waitForFunction(()=>![...document.querySelectorAll('[data-bank-list-row]')].some(r=>/OWNER PERSONAL/.test(r.textContent)&&r.dataset.bankState==='excluded'),null,{timeout:20000});
  const st=status('OWNER PERSONAL PURCHASE');await matchPost();const s=await rowsState();await home();const txt=await visText();return {ok:!ticked&&listed===1&&st==='pending'&&s['OWNER PERSONAL PURCHASE']==='Unposted'&&/2 Transactions To Post/i.test(txt),info:`opening the row's Actions menu ${ticked?'ticked the row':'left the row unticked'}; listed ${listed}; status ${st}; match-and-post ${s['OWNER PERSONAL PURCHASE']}; home ${(txt.match(/\d+ Transactions? To Post/i)||['none'])[0]}`}});
await matchPost();
await postOne('G-10','OWNER PERSONAL PURCHASE','3100','NO_TAX','3100 Owner Draws with no tax (the restored line)');
await t('G-11','Undo a posting: the bank fee is voided from the bank transaction list with a reason; its journal leaves the books (1000 and 6800 back by 25.00) and the line can be restored and posted again to the same figures; the old voided entry can then not be brought back on top of the new one',async()=>{
  const before=sql(`SELECT COALESCE(SUM(l.debit_cents-l.credit_cents),0) FROM journal_lines l JOIN journal_entries j ON j.id=l.journal_entry_id AND j.voided_at IS NULL JOIN accounts a ON a.id=l.account_id WHERE j.company_id='${CID}' AND a.code='6800'`);
  await p.locator('[data-r28-clear-bank]').click();await p.click('[data-r121-excluded]');await p.waitForSelector('[data-bank-list-row]',{timeout:20000}).catch(()=>{});await p.click('[data-filter="all"]');await p.waitForSelector('[data-bank-list-row][data-bank-state="posted"]:has-text("MONTHLY ACCOUNT FEE")',{timeout:20000});
  await rowAction('MONTHLY ACCOUNT FEE','[data-void-line]');await p.waitForSelector('#srp-void-form',{timeout:20000});const shown=await p.locator('.srp-void-table').innerText();
  await p.fill('#srp-void-form textarea[name=reason]','Posted twice by mistake in the guided test');await p.check('#srp-void-form input[name=confirmed]');await p.click('#srp-void-form button[type=submit]');await p.waitForSelector('#srp-void-form',{state:'detached',timeout:20000});
  const after=sql(`SELECT COALESCE(SUM(l.debit_cents-l.credit_cents),0) FROM journal_lines l JOIN journal_entries j ON j.id=l.journal_entry_id AND j.voided_at IS NULL JOIN accounts a ON a.id=l.account_id WHERE j.company_id='${CID}' AND a.code='6800'`),st=status('MONTHLY ACCOUNT FEE');
  await p.waitForSelector('[data-bank-list-row][data-bank-state="excluded"]:has-text("MONTHLY ACCOUNT FEE")',{timeout:20000});await rowAction('MONTHLY ACCOUNT FEE','[data-restore-line]');await p.waitForTimeout(1500);const st2=status('MONTHLY ACCOUNT FEE');
  await matchPost();await pick(['MONTHLY ACCOUNT FEE']);await fill('6800','NO_TAX');await submit(['MONTHLY ACCOUNT FEE']);const j=journal('MONTHLY ACCOUNT FEE');
  const feeId=sql(`SELECT id FROM bank_transactions WHERE company_id='${CID}' AND description='MONTHLY ACCOUNT FEE'`);const api=new S();await api.login('owner@gate.test','Gate!Owner#2026pw');api.cid=CID;const ur=await api.call('voids/restore',{method:'POST',json:{entityType:'bank_transaction',entityId:feeId,reason:'Trying to bring back the old voided entry'}});const unvoid=ur.s===409?'refused (409): '+(ur.b?.error||ur.b?.message||JSON.stringify(ur.b)).toString():'allowed ('+ur.s+')';
  const fee6800=sql(`SELECT COALESCE(SUM(l.debit_cents-l.credit_cents),0) FROM journal_lines l JOIN journal_entries j ON j.id=l.journal_entry_id AND j.voided_at IS NULL JOIN accounts a ON a.id=l.account_id WHERE j.company_id='${CID}' AND a.code='6800'`);
  return {ok:/^refused/.test(unvoid)&&Number(fee6800)===2500&&Number(before)===2500&&Number(after)===0&&st==='excluded'&&st2==='pending'&&norm(j)===norm(EXPECT['MONTHLY ACCOUNT FEE'])&&/25\.00/.test(shown),info:`restoring the old voided entry after the re-post: ${unvoid.slice(0,140)}; 6800 stays ${fee6800}; 6800 before ${before}, after void ${after}; status after void ${st}, after restore ${st2}; void preview "${shown.replace(/\s+/g,' ').slice(0,120)}"; re-posted ${norm(j)}`}});
await t('G-11b','The old voided fee posting stays history: restoring it through the journal route is refused and the books still show the fee once (6800 = 25.00)',async()=>{const api=new S();await api.login('owner@gate.test','Gate!Owner#2026pw');api.cid=CID;
  const old=sql(`SELECT id FROM journal_entries WHERE company_id='${CID}' AND source_type='bank_transaction_voided' LIMIT 1`);const r=await api.call('voids/restore',{method:'POST',json:{entityType:'journal',entityId:old,reason:'Trying the journal route back in'}});
  const fee=sql(`SELECT COALESCE(SUM(l.debit_cents-l.credit_cents),0) FROM journal_lines l JOIN journal_entries j ON j.id=l.journal_entry_id AND j.voided_at IS NULL JOIN accounts a ON a.id=l.account_id WHERE j.company_id='${CID}' AND a.code='6800'`);
  return {ok:!!old&&r.s===409&&Number(fee)===2500,info:`old voided posting ${old?'kept as bank_transaction_voided':'missing'}; journal-route restore ${r.s} ${(r.b?.error||'').slice(0,120)}; 6800 = ${fee}`}});
await t('G-12','Phone width (390 × 844): Guided Home and Match and Post have no sideways page scroll, status pills stay on one line, the Home to-do opens Match and Post, and "Adobe Software Subscription" posts to 6200 Software with GST/HST: Dr 6200 30.00 / Dr 1100 3.90 / Cr 1000 33.90',async()=>{errs.length=0;await p.setViewportSize({width:390,height:844});await p.goto('https://gate.test/app.html');await ready();await p.waitForTimeout(1500);
  const mode=await p.evaluate(()=>document.documentElement.dataset.bookkeepingMode);await p.waitForSelector('[data-guided-task-action="review"]',{timeout:30000});const homeOver=await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth);await p.click('[data-guided-task-action="review"]');await waitList();const over=await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth);await pick(['ADOBE SOFTWARE SUBSCRIPTION']);await p.locator('[data-r28-post-form]').scrollIntoViewIfNeeded();
  const prev=await fill('6200','ON');const btnBox=await p.locator('[data-r28-post]').boundingBox();await p.locator('[data-r28-post]').scrollIntoViewIfNeeded();await submit(['ADOBE SOFTWARE SUBSCRIPTION']);const j=journal('ADOBE SOFTWARE SUBSCRIPTION');const pills=await p.evaluate(()=>[...document.querySelectorAll('[data-r28-bank-row] .srp-status')].filter(x=>{const r=x.getBoundingClientRect(),lh=parseFloat(getComputedStyle(x).lineHeight)||16;return r.height>lh*1.6+8}).map(x=>x.textContent.trim()));const over2=await p.evaluate(()=>document.documentElement.scrollWidth-innerWidth);await p.screenshot({path:'/srv/gate/ev/shots/guided-phone-match-post.png'});
  return {ok:mode==='guided'&&over<=1&&over2<=1&&!pills.length&&homeOver<=1&&btnBox&&btnBox.x>=0&&btnBox.x+btnBox.width<=391&&norm(j)===norm(EXPECT['ADOBE SOFTWARE SUBSCRIPTION'])&&prevHas(prev,[3000,390,3390])&&!errs.length,info:`mode ${mode}; sideways overflow: Home ${homeOver}px, Match and Post ${over}px / after posting ${over2}px; status pills wrapped: ${pills.length?pills.join(','):'none'}; post button x ${btnBox&&Math.round(btnBox.x)}–${btnBox&&Math.round(btnBox.x+btnBox.width)}; preview ${prev.join(' / ')}; journal ${norm(j)}; errors ${errs.join(';')||'none'}`}});
await p.setViewportSize({width:1440,height:900});await p.goto('https://gate.test/app.html');await ready();await p.waitForTimeout(1200);
await t('G-13','All eight lines dealt with: Home shows no lines to post, offers "Bank Reconciliation" next, and the Banking badge is gone',async()=>{await home();const txt=await visText();const badge=await p.evaluate(()=>[...document.querySelectorAll('.sidebar nav button')].find(x=>/Banking/.test(x.textContent))?.querySelector('em')?.textContent.trim()||'');
  return {ok:!/Transactions? To Post/i.test(txt)&&/Bank Reconciliation/.test(txt)&&(!badge||badge==='0'),info:`to post shown ${/Transactions? To Post/i.test(txt)}; reconciliation task ${/Bank Reconciliation/.test(txt)}; badge "${badge}"`}});
await t('G-14','Match: in "Match transactions" the eight posted lines are offered as exact source pairs and one click matches all of them',async()=>{await matchPost();await p.click('[data-r28-mode="match"]');await p.waitForSelector('[data-r121-match-exact]',{timeout:20000});const label=(await p.locator('[data-r121-match-exact]').textContent()).trim();
  await p.click('[data-r121-match-exact]');await okDialog();await p.waitForFunction(()=>[...document.querySelectorAll('[data-r28-bank-row] .srp-status')].length===8&&[...document.querySelectorAll('[data-r28-bank-row] .srp-status')].every(x=>/Matched|Reconciled/.test(x.textContent)),null,{timeout:60000});
  const n=sql(`SELECT COUNT(*) FROM bank_transactions WHERE company_id='${CID}' AND status='posted'`);return {ok:/^Match 8 exact pairs$/i.test(label)&&n==='8',info:`button "${label}"; posted lines ${n}; all shown Matched`}});
const glNow=()=>Object.fromEntries(sql(`SELECT a.code,SUM(l.debit_cents-l.credit_cents) FROM journal_lines l JOIN journal_entries j ON j.id=l.journal_entry_id AND j.voided_at IS NULL AND j.status='posted' JOIN accounts a ON a.id=l.account_id WHERE j.company_id='${CID}' GROUP BY a.code HAVING SUM(l.debit_cents-l.credit_cents)<>0`).split('\n').filter(Boolean).map(x=>{const [c,v]=x.split('\t');return [c,Number(v)]}));
await t('G-15','General Ledger after the Guided session equals the hand-worked balances: Bank 183.60 Dr, GST/HST recoverable 36.40 Dr, GST/HST payable 65.00 Cr, revenue 500.00 Cr, expenses 305.00 Dr, owner draws 40.00 Dr; debits equal credits',async()=>{const g=glNow();const sum=Object.values(g).reduce((s,v)=>s+v,0);
  return {ok:JSON.stringify(Object.entries(g).sort())===JSON.stringify(Object.entries(FINAL).sort())&&sum===0,info:`got ${JSON.stringify(g)}; want ${JSON.stringify(FINAL)}; net ${sum}`}});
await t('G-16','Month-end checklist from Guided Home (shortcut "Month-End Checklist"): statement transactions and trial balance are ticked, and the bank reconciliation is flagged as still to do',async()=>{await home();const sc=p.locator('[data-guided-shortcut="monthEnd"]');const has=await sc.count();if(!has)return {ok:false,info:'Guided Home has no way to open the Guided month-end checklist'};
  await sc.click();await p.waitForSelector('.tegh-guided-checklist article',{timeout:20000});const items=await p.evaluate(()=>Object.fromEntries([...document.querySelectorAll('.tegh-guided-checklist article')].map(a=>[a.querySelector('b').textContent.trim(),a.className])));
  return {ok:items['Statement transactions']==='pass'&&items['Trial balance']==='pass'&&items['Bank reconciliation']==='attention',info:JSON.stringify(items)}});
await t('G-17','Owner reports agree with the hand-worked figures: Home shows money in the bank $183.60, GST/HST owed $28.60 (65.00 − 36.40) and profit $195.00 (500.00 − 305.00); Profit and Loss shows net income 195.00',async()=>{await p.evaluate(()=>TeghPortal.openDashboard());await p.waitForTimeout(3500);const d=await visText();
  await p.evaluate(()=>TeghPortal.openReport('Profit and Loss'));await p.waitForTimeout(4000);const pl=await visText();
  return {ok:d.includes('$183.60')&&d.includes('$28.60')&&d.includes('$195.00')&&pl.includes('195.00'),info:`home bank ${d.includes('$183.60')}, tax ${d.includes('$28.60')}, profit ${d.includes('$195.00')}; P&L ${pl.includes('195.00')}`}});
const errsAll=(await import('./lib.mjs')).results.filter(r=>/errors (?!none)/.test(r.evidence));
rec('G-18',A,'No script errors on any Guided screen during the session',errsAll.length?'FAIL':'PASS',errsAll.length?errsAll.map(r=>r.id).join(','):'no page errors recorded in G-03…G-12');
fs.writeFileSync('/srv/gate/ev/guided-company.json',JSON.stringify({companyId:CID,name:setup.name}));
await b.close();save('guided.json');
