import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';import fs from 'fs';
const [,, W='1440', H='900', tag='desk']=process.argv;const vw=+W,vh=+H,mobile=vw<800;const ids=JSON.parse(fs.readFileSync('/srv/gate/t/ids.json'));
const browser=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',args:['--no-proxy-server','--host-resolver-rules=MAP gate.test 127.0.0.1']});
const ctx=await browser.newContext({viewport:{width:vw,height:vh},isMobile:mobile,hasTouch:mobile,ignoreHTTPSErrors:true});const IDS=JSON.parse(fs.readFileSync('/srv/gate/t/ids.json'));await ctx.addInitScript(id=>{try{if(!sessionStorage.getItem('gate-co')){localStorage.setItem('sr-accountax-company',id);localStorage.setItem('sr-accountax-companies',JSON.stringify([id]));sessionStorage.setItem('gate-co','1')}}catch{}},process.env.GATE_COMPANY?IDS[process.env.GATE_COMPANY]:IDS.BC);const page=await ctx.newPage();
const ext=[];page.on('request',r=>{const u=r.url();if(!u.startsWith('https://gate.test'))ext.push(u.split('?')[0])});
await page.route(/challenges\.cloudflare|googleapis|gstatic/,r=>r.abort());
const errs=[];page.on('pageerror',e=>errs.push(e.message.slice(0,140)));page.on('dialog',d=>{errs.push('DIALOG '+d.message().slice(0,60));d.dismiss()});
const log=[];const shot=async(n,fn,check)=>{try{await fn();await page.waitForTimeout(2200);const info=check?await page.evaluate(check):'';await page.screenshot({path:`/srv/gate/ev/shots/journey-${tag}-${n}.png`});log.push({n,ok:true,info,errs:[...errs]})}catch(e){log.push({n,ok:false,err:e.message.slice(0,160)})}errs.length=0};
await shot('01-signin',()=>page.goto('https://gate.test/app.html'));
await page.fill('#sr-login-form input[name=email]','owner@gate.test');await page.fill('#sr-login-form input[name=password]','Gate!Owner#2026pw');await page.click('#sr-login-form button[type=submit]');
await page.waitForFunction(()=>window.TeghPortal&&document.querySelector('.sidebar,.topbar'),null,{timeout:40000});
const sw=async id=>{await page.evaluate(id=>{localStorage.setItem('sr-accountax-company',id);localStorage.setItem('sr-accountax-companies',JSON.stringify([id]))},id);await page.goto('https://gate.test/app.html');await page.waitForFunction(()=>window.TeghPortal&&document.querySelector('.sidebar,.topbar'),null,{timeout:40000});await page.waitForTimeout(2000)};
await sw(ids.ON);
await shot('02-dashboard-ON-custom-tax',()=>page.evaluate(()=>window.TeghPortal.openDashboard()),()=>[...document.querySelectorAll('.srp-page *')].map(e=>e.children.length?'':e.textContent).join(' ').match(/other tax accounts[^·)]*\)?/)?.[0]||'no other-tax line');
await sw(ids.BC);
await shot('03-tax-codes',()=>page.evaluate(()=>window.TeghPortal.openTaxCodes()),()=>document.querySelector('.srp-page h1')?.textContent);
await shot('04-new-invoice-BC',()=>page.evaluate(()=>window.TeghPortal.openInvoice()),()=>document.querySelector('.srp-page h1')?.textContent);
await shot('05-gl-journal',()=>page.evaluate(()=>window.TeghPortal.openManualJournals()),()=>{const o=[...document.querySelectorAll('.srp-page select option')].map(x=>x.textContent);return 'AR/AP offered: '+o.some(t=>/^\s*(1200|2050)\b/.test(t))+' ('+o.length+' options)'});
await shot('06-customers-xss',()=>page.evaluate(()=>window.TeghPortal.openCustomers()),()=>'xss executed: '+(!!window.__xss)+'; evil name shown as text: '+document.body.innerText.includes('<img src=x'));
await shot('07-match-and-post',()=>page.evaluate(()=>window.TeghPortal.openBankReview()),()=>document.querySelector('.srp-page h1')?.textContent);
await shot('08-trial-balance',()=>page.evaluate(()=>window.TeghPortal.openPeriodTrialBalance()),()=>document.querySelector('.srp-page h1')?.textContent);
await sw(ids.NR);
await shot('09-unregistered-invoice',()=>page.evaluate(()=>window.TeghPortal.openInvoice()),()=>[...document.querySelectorAll('.srp-page select option')].map(o=>o.textContent).find(t=>/Not registered/.test(t))||'label missing');
fs.writeFileSync(`/srv/gate/ev/journeys-${tag}.json`,JSON.stringify({tag,external:[...new Set(ext)],log},null,1));console.log(tag,'external requests:',[...new Set(ext)].join(',')||'none');for(const l of log)console.log(' ',l.n,l.ok?'ok':'ERR '+l.err,l.info||'',l.errs?.length?'JS: '+l.errs.join(';'):'');
await browser.close();
