// R144 browser checks on the seeded "R144 Insights Inc" company (15-r144.mjs). Figures were worked out by hand there.
import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';import fs from 'fs';import {sql,rec,save} from './lib.mjs';
const [,, W='1440', H='900', tag='desk']=process.argv;const vw=+W,vh=+H,mobile=vw<800;const ids=JSON.parse(fs.readFileSync('/srv/gate/t/ids.json'));const CID=ids.R144;const A='R144UI';
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium',args:['--no-proxy-server','--host-resolver-rules=MAP gate.test 127.0.0.1']});
const ctx=await b.newContext({viewport:{width:vw,height:vh},isMobile:mobile,hasTouch:mobile,ignoreHTTPSErrors:true});
const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message.slice(0,160)));p.on('dialog',d=>d.accept());
const shot=n=>p.screenshot({path:`/srv/gate/ev/shots/r144-${tag}-${n}.png`});
const page=()=>p.locator('.srp-page').last();
const confirm=async()=>{for(let i=0;i<12;i++){const c=p.locator('dialog[open] button, [role=dialog] button, .srp-modal button').filter({hasText:/^(Continue|Confirm|Yes|OK)\b/});if(await c.count()){await c.last().click();await p.waitForTimeout(1200);return}await p.waitForTimeout(250)}};
await p.goto('https://gate.test/app.html');await p.fill('#sr-login-form input[name=email]','owner@gate.test');await p.fill('#sr-login-form input[name=password]','Gate!Owner#2026pw');await p.click('#sr-login-form button[type=submit]');
await p.waitForFunction(()=>window.TeghPortal&&document.querySelector('.sidebar,.topbar'),null,{timeout:40000});
await p.evaluate(id=>{localStorage.setItem('sr-accountax-company',id);localStorage.setItem('sr-accountax-companies',JSON.stringify([id]))},CID);await p.goto('https://gate.test/app.html');await p.waitForFunction(()=>window.TeghPortal&&document.querySelector('.sidebar,.topbar'),null,{timeout:40000});await p.waitForTimeout(1500);
const t=async(id,title,fn)=>{try{const r=await fn();rec(`${id}-${tag}`,A,title,r.ok?'PASS':'FAIL',r.info||'')}catch(e){rec(`${id}-${tag}`,A,title,'FAIL',e.message.split('\n')[0].slice(0,200));await shot('fail-'+id)}};
await t('UI-01','Dashboard shows the Tegh brief with the cash line ($4,887.00) and a link to all insights',async()=>{await p.evaluate(()=>TeghPortal.openDashboard());const br=p.locator('[data-r144-brief]');await br.locator('li').first().waitFor({timeout:15000});const txt=(await br.textContent()).replace(/\s+/g,' ');await shot('01-dashboard');return {ok:/Cash in the bank is \$4,887\.00/.test(txt)&&await br.locator('[data-r144-open-insights]').count()===1&&(await br.locator('li').count())>=6,info:txt.slice(0,160)}});
await t('UI-02','"See all insights" opens Tegh Intelligence with findings, the chase list (Lakeview Dental first) and the cash chart',async()=>{await p.locator('[data-r144-open-insights]').click();await page().locator('.r144-findings li').first().waitFor({timeout:15000});const pg=page();const h=await pg.locator('h1').first().textContent();const first=(await pg.locator('.r144-chase li').first().textContent()).replace(/\s+/g,' ');await shot('02-insights');return {ok:/Tegh Intelligence/.test(h)&&(await pg.locator('.r144-findings li').count())>=6&&/^Lakeview Dental/.test(first.trim())&&await pg.locator('.r144-chart svg rect').count()===6&&await pg.locator('.r144-table table').count()===1,info:`${h} | ${first.slice(0,60)}`}});
await t('UI-03','"Not a problem" marks a finding, and Undo restores it',async()=>{const pg=page();const n0=await pg.locator('.r144-findings li:not([data-dismissed])').count();await pg.locator('[data-r144-finding-dismiss]').first().click();await p.waitForTimeout(1500);const n1=await page().locator('.r144-findings li').count();const tog=page().locator('[data-r144-toggle-dismissed]');const togOk=await tog.count()===1;await tog.click();await p.waitForTimeout(500);await page().locator('.r144-findings li[data-dismissed] [data-r144-finding-dismiss]').first().click();await p.waitForTimeout(1500);const n2=await page().locator('.r144-findings li:not([data-dismissed])').count();return {ok:n1===n0-1&&togOk&&n2===n0,info:`${n0}→${n1}→${n2}`}});
await t('UI-04','What-if: adding $1,000 a month shows a runway sentence',async()=>{const wi=page().locator('[data-r144-whatif]');await wi.fill('1000');await p.waitForTimeout(300);const out=await page().locator('[data-r144-whatif-result]').textContent();return {ok:/\$1,000\.00 more a month/.test(out),info:out}});
await t('UI-05','A finding\'s Open button goes to its screen (duplicate vendor invoice → Vendor Invoice Register)',async()=>{const li=page().locator('.r144-findings li',{hasText:'Possible duplicate vendor invoice'}).first();await li.locator('[data-r144-finding-open]').click();await p.waitForTimeout(2500);const h=await page().locator('h1').first().textContent();return {ok:/Vendor Invoice/i.test(h),info:h}});
await t('UI-06','Match and Post: the pending Rogers line shows "Suggested: 6300 · Telephone and Internet · 67% sure"; Use suggestion fills the account and tax code',async()=>{await p.evaluate(()=>TeghPortal.invokeMenuAction('Banking','Match and Post Transactions'));await p.waitForTimeout(4000);const pg=page();const f=pg.locator('[data-r28-filter]');if(await f.count()){await f.locator('[name=start]').fill('2026-08-01');await pg.locator('button:visible',{hasText:/^Refresh$/}).click();await p.waitForTimeout(3000)}
  await pg.locator('tr',{hasText:'ROGERS WIRELESS'}).filter({hasText:'Unposted'}).locator('input[type=checkbox]').first().check({force:true});const box=pg.locator('[data-r144-suggestion]');await box.waitFor({timeout:10000});const txt=(await box.textContent()).replace(/\s+/g,' ');await shot('06-suggestion');
  await box.locator('[data-r144-use]').click();await p.waitForTimeout(800);const acct=await pg.locator('select[name=accountId]').filter({visible:true}).evaluate(s=>s.options[s.selectedIndex].text);const tax=await pg.locator('select[name=taxCode]').filter({visible:true}).evaluate(s=>s.options[s.selectedIndex].text);const status=sql(`SELECT status FROM bank_transactions WHERE company_id='${CID}' AND reference='R3'`);
  return {ok:/Suggested: 6300 · Telephone and Internet/.test(txt)&&/67% sure/.test(txt)&&/2 times/.test(txt)&&/^6300/.test(acct)&&/^ON/.test(tax)&&status==='pending',info:`${txt.slice(0,120)} | ${acct} | ${tax} | still ${status}`}});
const ask=async q=>{await p.evaluate(()=>document.querySelectorAll('.tegh-assist-scrim').forEach(n=>n.remove()));await p.locator('button').filter({hasText:/^Tegh Assist$/}).first().click();const inp=p.locator('.tegh-assist-drawer [data-command-free-text] input');await inp.waitFor({timeout:15000});await inp.fill(q);await inp.press('Enter');await p.waitForTimeout(2500)};
await t('UI-07','Tegh Assist answers "how much did I spend on telephone this year" from the books: $1,000.00',async()=>{await ask('how much did I spend on telephone this year');const a=(await p.locator('[data-r144-answer]').first().textContent()).replace(/\s+/g,' ');await shot('07-assist');return {ok:/You spent \$1,000\.00 on 6300 Telephone and Internet/.test(a)&&/Worked out by Tegh from your posted books/.test(a),info:a.slice(0,140)}});
await t('UI-08','Tegh Assist "top customers this year" lists Lakeview Dental first',async()=>{await p.keyboard.press('Escape');await ask('who are my top customers this year');const a=(await p.locator('[data-r144-answer]').first().textContent()).replace(/\s+/g,' ');return {ok:/Lakeview Dental/.test(a)&&/\$2,000\.00/.test(a),info:a.slice(0,140)}});
await t('UI-09','Tegh Assist "anything unusual?" opens Tegh Intelligence',async()=>{await p.keyboard.press('Escape');await ask('anything unusual?');await p.waitForTimeout(1500);const h=await page().locator('h1').first().textContent();return {ok:/Tegh Intelligence/.test(h),info:h}});
await t('UI-10','Ordinary Assist requests still route as before ("who owes me money" → receivables answer)',async()=>{await ask('who owes me money');await p.waitForTimeout(1500);const a=(await p.locator('.tegh-assist-drawer [data-command-result]').textContent()).replace(/\s+/g,' ');return {ok:/Receivable Ageing/.test(a)&&/3,649\.00|2,599\.00/.test(a)&&!/data-r144-answer/.test(a),info:a.slice(0,160)}});
rec(`UI-JS-${tag}`,A,'No JavaScript errors',errs.length?'FAIL':'PASS',errs.join(' | ').slice(0,300));
await b.close();save('r144ui.json');
