// R145 synthetic bills and receipts (fictional businesses and amounts) for Document Intake.
// Expected fields are written by hand below; tax/total arithmetic is plain integer cents.
import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';import fs from 'fs';
const OUT='/srv/gate/t/conv/dx';
const doc=(w,body,extra='')=>`<!doctype html><html><head><meta charset="utf-8"><style>body{margin:0;font:14px Arial;color:#111;${extra}}.p{width:${w}px;padding:28px}.r{display:flex;justify-content:space-between;gap:24px}table{border-collapse:collapse;width:100%}td,th{padding:4px 6px;text-align:left}td.n,th.n{text-align:right}</style></head><body><div class="p">${body}</div></body></html>`;
const docs={
 I1:{kind:'pdf',html:doc(760,`<div class="r"><div><b style="font-size:20px">Northwind Office Supply Ltd.</b><br>123 Queen Street West, Toronto ON M5H 2M9<br>GST/HST Registration No: 812345678 RT0001</div><div><b style="font-size:22px">INVOICE</b></div></div>
  <div class="r" style="margin-top:20px"><div>Bill To: Riverbend Test Co</div><div>Invoice Number: INV-20418<br>Invoice Date: 2026-03-04<br>Due Date: 2026-04-03</div></div>
  <table style="margin-top:20px"><tr><th>Description</th><th class="n">Qty</th><th class="n">Unit Price</th><th class="n">Amount</th></tr><tr><td>Printer paper (case)</td><td class="n">4</td><td class="n">45.00</td><td class="n">180.00</td></tr><tr><td>Toner cartridge</td><td class="n">2</td><td class="n">89.50</td><td class="n">179.00</td></tr></table>
  <div style="margin-top:16px;margin-left:420px"><div class="r"><span>Subtotal</span><span>$359.00</span></div><div class="r"><span>HST 13%</span><span>$46.67</span></div><div class="r"><b>Total</b><b>$405.67</b></div><div class="r"><span>Amount Due</span><span>$405.67</span></div></div><p>Terms: Net 30</p>`),
  want:{partyName:'Northwind Office Supply Ltd.',documentNumber:'INV-20418',documentDate:'2026-03-04',dueDate:'2026-04-03',subtotalCents:35900,taxCents:4667,totalCents:40567,businessIdentifier:'812345678 RT0001',lineItems:2}},
 I2:{kind:'pdf',html:doc(760,`<b style="font-size:20px">Quincaillerie Laval Inc.</b><br>88 boul. des Tests, Laval QC<br><b style="font-size:22px">FACTURE</b><br>Facture n° F-7781<br>Date de facture : 15 mars 2026
  <table style="margin-top:16px"><tr><th>Description</th><th class="n">Montant</th></tr><tr><td>Vis à bois (boîte)</td><td class="n">12,50 $</td></tr><tr><td>Perceuse sans fil</td><td class="n">149,00 $</td></tr></table>
  <div style="margin-left:420px;margin-top:12px"><div class="r"><span>Sous-total</span><span>161,50 $</span></div><div class="r"><span>TPS 5 %</span><span>8,08 $</span></div><div class="r"><span>TVQ 9,975 %</span><span>16,11 $</span></div><div class="r"><b>Total</b><b>185,69 $</b></div></div><p>TPS : 123456789 RT0001 · TVQ : 1234567890 TQ0001</p>`),
  want:{partyName:'Quincaillerie Laval Inc.',documentNumber:'F-7781',documentDate:'2026-03-15',subtotalCents:16150,taxCents:2419,totalCents:18569,lineItems:2}},
 I3:{kind:'png',width:380,scale:1,html:doc(330,`<div style="text-align:center"><b>GREENLEAF GROCERY #22</b><br>1450 Main St, Oakfield ON<br>(905) 555-0182</div><br>03/04/2026 14:22<br>Receipt # 0042-118<br><br>
  <div class="r"><span>BANANAS</span><span>2.99</span></div><div class="r"><span>COFFEE BEANS 1KG</span><span>18.99</span></div><br><div class="r"><span>SUBTOTAL</span><span>21.98</span></div><div class="r"><span>HST 13%</span><span>1.43</span></div><div class="r"><b>TOTAL</b><b>23.41</b></div><div class="r"><span>VISA TEND</span><span>23.41</span></div><br>HST # 123456789 RT0001<br><div style="text-align:center">THANK YOU</div>`,'background:#e9e4d8;font-family:Courier New,monospace;'),
  want:{partyName:'GREENLEAF GROCERY #22',documentNumber:'0042-118',documentDate:'',alternatives:['2026-03-04','2026-04-03'],subtotalCents:2198,taxCents:143,totalCents:2341}},
 I4:{kind:'scan',html:doc(760,`<b style="font-size:22px">Harbour Freight Logistics</b><br>9 Dockside Road, Halifax NS<br><br><b style="font-size:20px">Invoice</b><br><br>Invoice # HF-5520<br>Date: Mar 20, 2026<br>Payment Terms: Net 15<br><br>
  <div style="margin-left:380px"><div class="r"><span>Subtotal</span><span>1,200.00</span></div><div class="r"><span>GST</span><span>60.00</span></div><div class="r"><span>PST</span><span>84.00</span></div><div class="r"><b>Total Amount Due</b><b>1,344.00</b></div></div>`),
  want:{partyName:'Harbour Freight Logistics',documentNumber:'HF-5520',documentDate:'2026-03-20',dueDate:'2026-04-04',subtotalCents:120000,taxCents:14400,totalCents:134400}},
 I6:{kind:'png',width:250,scale:1,html:doc(220,`<div style="text-align:center"><b>MAPLE LEAF CAFE</b></div>2026-08-21 09:41<br>Receipt # 7781<br><div class="r"><span>LATTE</span><span>5.25</span></div><div class="r"><span>MUFFIN</span><span>3.75</span></div><div class="r"><span>SUBTOTAL</span><span>9.00</span></div><div class="r"><span>HST</span><span>1.17</span></div><div class="r"><b>TOTAL</b><b>10.17</b></div>`,'background:#9a958c;color:#4a463f;font-size:11px;font-family:Courier New,monospace;'),
  want:{partyName:'MAPLE LEAF CAFE',documentNumber:'7781',documentDate:'2026-08-21',subtotalCents:900,taxCents:117,totalCents:1017}},
 I7:{kind:'scan',html:doc(760,`<div style="font-size:11px"><b>Birchwood Courier Ltd.</b><br>Invoice # BC-311<br>Date: Jul 7, 2026<br><br>Subtotal 80.00<br>HST 10.40<br><b>Total 90.40</b></div>`),
  want:{partyName:'Birchwood Courier Ltd.',documentNumber:'BC-311',documentDate:'2026-07-07',subtotalCents:8000,taxCents:1040,totalCents:9040}},
 I5:{kind:'png',width:360,scale:1,html:doc(310,`<div style="text-align:center"><b>FIELDSTONE FUEL 0091</b></div><br>2026/09/14 08:12<br>PUMP 4 REGULAR 52.300 L<br><div class="r"><span>FUEL SALE</span><span>$ 81.07</span></div><div class="r"><span>GST/HST INCLUDED</span><span>$ 9.33</span></div><div class="r"><b>TOTAL</b><b>$ 81.07</b></div><div class="r"><span>MASTERCARD</span><span>$ 81.07</span></div>`,'background:#f2efe6;font-family:Courier New,monospace;'),
  want:{partyName:/^FIELDSTONE FUEL \d{4}$/,documentDate:'2026-09-14',subtotalCents:7174,taxCents:933,totalCents:8107}},
};
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
for(const [k,d] of Object.entries(docs)){
  if(d.kind==='pdf'){const p=await b.newPage();await p.setContent(d.html);await p.pdf({path:`${OUT}/${k}.pdf`,format:'Letter'});await p.close()}
  else if(d.kind==='png'){const p=await b.newPage({viewport:{width:d.width,height:600},deviceScaleFactor:d.scale});await p.setContent(d.html);await p.screenshot({path:`${OUT}/${k}.png`,fullPage:true});await p.close()}
  else {const p=await b.newPage({viewport:{width:816,height:1056},deviceScaleFactor:2.08});await p.setContent(d.html);const png=await p.screenshot({fullPage:false});await p.setContent(`<!doctype html><body style="margin:0"><img src="data:image/png;base64,${png.toString('base64')}" style="width:816px"></body>`);await p.pdf({path:`${OUT}/${k}.pdf`,width:'816px',height:'1056px'});await p.close()}
}
await b.close();fs.writeFileSync(`${OUT}/expected.json`,JSON.stringify(Object.fromEntries(Object.entries(docs).map(([k,d])=>[k,{kind:d.kind,want:Object.fromEntries(Object.entries(d.want).map(([f,v])=>[f,v instanceof RegExp?{re:v.source}:v]))}])),null,1));console.log('ok');
